/****************************************************************************
 * COPYRIGHT VITESCO TECHNOLOGIES GROUP AG (EXCLUSIVE RIGHTS) 
 * Confidential
 * 
 * The reproduction, transmission or use of this document or its
 * contents is not permitted without express written authority.
 * Offenders will be liable for damages. All rights, including rights
 * created by patent grant or registration of a utility model or design,
 * are reserved.
 *---------------------------------------------------------------------------
 * 
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 * !!! This file is generated by Signal Mapper (SIMA) Code-Generator !!!
 * !!! Do NOT modify this file manually                            !!!
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 * 
 * Purpose:    PL Hook Implementation
 * 
 * Processor:  independent
 * Tool chain: 
 *    CG-Version:        6.2.0
 *    Schema-Version:    1.18.0
 *    Generation-Date:   29.08.2024  16:51:03  
 *    Generated by user: uiv00534
 * Filename:   $Workfile$
 * Revision:   $Revision: 1.1 $
 * Author:     $Author: Zhang Yi (uiv00534) (uiv00534) $
 * Date:       $Date: 2024/09/03 03:13:03CEST $
 * Changes:    $Log: ipl_hook_rx_priv.c  $
 * Changes:    Revision 1.1 2024/09/03 03:13:03CEST Zhang Yi (uiv00534) (uiv00534) 
 * Changes:    Initial revision
 * Changes:    Member added to project /ES/FS/0G/H0D/0A/bsw/intc/intc_sigcv_cclu1/i/project.pj
 * 
****************************************************************************/
/*lint -esym(750,IPL_HOOK_RX_PRIV_C) */
#define IPL_HOOK_RX_PRIV_C
#include <intc_sigcv_cclu1_im.h>


#undef ACTION_ID
#define ACTION_ID ACTION_ID_PL_Cvt_EduPriv_ACU_ConSt
/*lint  -efile(451,ipl_hook_rx_priv_mcr.h) */
#include <ipl_hook_rx_priv_mcr.h>
#define  MEM_CODE            ICS_PL_MEM_CODE_SERVICE
#include <gmem.h>
/*lint  -efunc(774,PL_Cvt_EduPriv_ACU_ConSt) */
ICS_PL_RETURN_TYPE PL_Cvt_EduPriv_ACU_ConSt(void)
{
    /* Conversion for RX-Bus-Signal 'EduPriv_ACU_ConSt' */
    
    /* Allocate temporary variables */
    ICS_PL_RETURN_TYPE tmp_return_value = ICS_PL_TRUE;
    ICS_PL_U8 bus_cpy;
    ICS_PL_U8 sys_cpy0 = 0U;
    
    
    /* Source-Signal Description: */
    /*     Name: EduPriv_ACU_ConSt(intc_sigcv_rx_priv) */
    /*     Category, Type, length, Interface: TEXT, ICS_PL_U8, 4 bits, API */
    /*     Desc: Actual connection state */
    /*     State(s): [0x0...    ] */
    /*     Text definitions (Name [CLL, CUL]) */
    /*     Fault [0x4; 0x4] */
    /*     Connected (end-stop reached) [0x3; 0x3] */
    /*     In Transition (pot. connected) [0x2; 0x2] */
    /*     Disconnected [0x1; 0x1] */
    /*     Init [0x0; 0x0] */
    
    /* Destination-Signal Description: */
    /*     Name: Pl_AcuConnectionSt(intc_sigcv_rx_priv) */
    /*     Category, Type, Interface: TEXT, ICS_PL_U8, VAR */
    /*     Desc: Operational state of electrical machine clutch */
    /*     Text definitions (Name [CLL, CUL]) */
    /*     INI [0x0; 0x0] */
    /*     DISCNCT [0x1; 0x1] */
    /*     TRAN [0x2; 0x2] */
    /*     CNCT [0x3; 0x3] */
    /*     ERR [0x4; 0x4] */
    /*     Variable-Name: Pl_AcuConnectionSt */
    
    /* Mapping Description: */
    /*     ID: intc_sigcv_rx_priv_Mapping00072 */
    /*     Processing: UNCONDITIONAL */
    /*     Text Mapping */
    /*     SRC -> DST */
    /*     Init[0x0] -> INI[0x0] */
    /*     Disconnected[0x1] -> DISCNCT[0x1] */
    /*     In Transition (pot. connected)[0x2] -> TRAN[0x2] */
    /*     Connected (end-stop reached)[0x3] -> CNCT[0x3] */
    /*     Fault[0x4] -> ERR[0x4] */
    /*     Limit-Handling: automatically limit Dst-Signal */
    /*     Conversion-Handling: Internal conversion */
    /*     Out-Off-Range-Handling: Cancel conversion if Src-Signal is out of valid range */
    
    /* Copy SRC to temporary-src-container */
    bus_cpy = 0U;
    if(READ_SIGNAL_DATA_API(EduPriv_ACU_ConSt, &bus_cpy) == READ_SIGNAL_DATA_API_SUCCESS)
    {
        
        if(bus_cpy == 0U)
        {
            /* Map SRC-Value 'Init' to DST-Value 'INI' */
            sys_cpy0 = 0U;
        }
        else if(bus_cpy == 1U)
        {
            /* Map SRC-Value 'Disconnected' to DST-Value 'DISCNCT' */
            sys_cpy0 = 1U;
        }
        else if(bus_cpy == 2U)
        {
            /* Map SRC-Value 'In Transition (pot. connected)' to DST-Value 'TRAN' */
            sys_cpy0 = 2U;
        }
        else if(bus_cpy == 3U)
        {
            /* Map SRC-Value 'Connected (end-stop reached)' to DST-Value 'CNCT' */
            sys_cpy0 = 3U;
        }
        else if(bus_cpy == 4U)
        {
            /* Map SRC-Value 'Fault' to DST-Value 'ERR' */
            sys_cpy0 = 4U;
        }
        else
        {
            /* SRC is not within the valid COD-range => cancel processing */
            tmp_return_value = ICS_PL_FALSE;
        }
        if(tmp_return_value == ICS_PL_TRUE)
        {
            /* Copy temporary-dst-container to DST */
            SET_Pl_AcuConnectionSt(sys_cpy0);
        }
        else
        {
            /* Nothing to do here */
        }
    }
    else
    {
        tmp_return_value = ICS_PL_FALSE;
    }
    
    return tmp_return_value;
}
#undef ACTION_ID
#define ACTION_ID ACTION_ID_PL_Cvt_EduPriv_ACU_EmSpdCtrlModReq
/*lint  -efile(451,ipl_hook_rx_priv_mcr.h) */
#include <ipl_hook_rx_priv_mcr.h>
#define  MEM_CODE            ICS_PL_MEM_CODE_SERVICE
#include <gmem.h>
/*lint  -efunc(774,PL_Cvt_EduPriv_ACU_EmSpdCtrlModReq) */
ICS_PL_RETURN_TYPE PL_Cvt_EduPriv_ACU_EmSpdCtrlModReq(void)
{
    /* Conversion for RX-Bus-Signal 'EduPriv_ACU_EmSpdCtrlModReq' */
    
    /* Allocate temporary variables */
    ICS_PL_RETURN_TYPE tmp_return_value = ICS_PL_TRUE;
    ICS_PL_FLAG bus_cpy;
    ICS_PL_FLAG sys_cpy0 = ICS_PL_FALSE;
    
    
    /* Source-Signal Description: */
    /*     Name: EduPriv_ACU_EmSpdCtrlModReq(intc_sigcv_rx_priv) */
    /*     Category, Type, length, Interface: TEXT, ICS_PL_FLAG, 1 bits, API */
    /*     Desc: Request by ACU to PE for EM speed control mode */
    /*     State(s): [0x0...    ] */
    /*     Text definitions (Name [CLL, CUL]) */
    /*     EM speed control requested [0x1; 0x1] */
    /*     EM speed control not requested [0x0; 0x0] */
    
    /* Destination-Signal Description: */
    /*     Name: Pl_AcuEmSpdCtlModReq(intc_sigcv_rx_priv) */
    /*     Category, Type, Interface: TEXT, ICS_PL_FLAG, VAR */
    /*     Desc: Clutch is requesting to activate speed control */
    /*     Text definitions (Name [CLL, CUL]) */
    /*     FALSE [0x0; 0x0] */
    /*     TRUE [0x1; 0x1] */
    /*     Variable-Name: Pl_AcuEmSpdCtlModReq */
    
    /* Mapping Description: */
    /*     ID: intc_sigcv_rx_priv_Mapping00073 */
    /*     Processing: UNCONDITIONAL */
    /*     Text Mapping */
    /*     SRC -> DST */
    /*     EM speed control not requested[0x0] -> FALSE[0x0] */
    /*     EM speed control requested[0x1] -> TRUE[0x1] */
    /*     Limit-Handling: automatically limit Dst-Signal */
    /*     Conversion-Handling: Internal conversion */
    /*     Out-Off-Range-Handling: Cancel conversion if Src-Signal is out of valid range */
    
    /* Copy SRC to temporary-src-container */
    bus_cpy = ICS_PL_FALSE;
    if(READ_SIGNAL_DATA_API(EduPriv_ACU_EmSpdCtrlModReq, &bus_cpy) == READ_SIGNAL_DATA_API_SUCCESS)
    {
        
        if(bus_cpy == ICS_PL_FALSE)
        {
            /* Map SRC-Value 'EM speed control not requested' to DST-Value 'FALSE' */
            sys_cpy0 = ICS_PL_FALSE;
        }
        else
        {
            /* Map SRC-Value 'EM speed control requested' to DST-Value 'TRUE' */
            sys_cpy0 = ICS_PL_TRUE;
        }
        /* Copy temporary-dst-container to DST */
        SET_Pl_AcuEmSpdCtlModReq(sys_cpy0);
    }
    else
    {
        tmp_return_value = ICS_PL_FALSE;
    }
    
    return tmp_return_value;
}
#undef ACTION_ID
#define ACTION_ID ACTION_ID_PL_Cvt_EduPriv_ACU_EmSpdTgt
/*lint  -efile(451,ipl_hook_rx_priv_mcr.h) */
#include <ipl_hook_rx_priv_mcr.h>
#define  MEM_CODE            ICS_PL_MEM_CODE_SERVICE
#include <gmem.h>
/*lint  -efunc(774,PL_Cvt_EduPriv_ACU_EmSpdTgt) */
ICS_PL_RETURN_TYPE PL_Cvt_EduPriv_ACU_EmSpdTgt(void)
{
    /* Conversion for RX-Bus-Signal 'EduPriv_ACU_EmSpdTgt' */
    
    /* Allocate temporary variables */
    ICS_PL_RETURN_TYPE tmp_return_value = ICS_PL_TRUE;
    ICS_PL_U16 bus_cpy;
    ICS_PL_S16 sys_cpy0 = 0;
    
    
    /* Source-Signal Description: */
    /*     Name: EduPriv_ACU_EmSpdTgt(intc_sigcv_rx_priv) */
    /*     Category, Type, length, Interface: NUM, ICS_PL_U16, 16 bits, API */
    /*     Desc: ACU EM target speed */
    /*     State(s): [0x7D00...    ] */
    /*     Coded Range: [0x0...0xFFFF] */
    /*     Harmonized Physical Range: [-16000...16767.5] [rpm] */
    /*     Original Physical Range: [-16000...16767.5] [rpm] */
    
    /* Destination-Signal Description: */
    /*     Name: Pl_AcuEmSpdTar(intc_sigcv_rx_priv) */
    /*     Category, Type, Interface: NUM, ICS_PL_S16, VAR */
    /*     Desc: Electrical machine speed requested by clutch */
    /*     Coded Range: [0x8000...0x7FFF] */
    /*     Harmonized Physical Range: [-32768...32767] [PD_rpm] */
    /*     Original Physical Range: [-32768...32767] [rpm] */
    /*     Variable-Name: Pl_AcuEmSpdTar */
    
    /* Mapping Description: */
    /*     ID: intc_sigcv_rx_priv_Mapping00074 */
    /*     Processing: UNCONDITIONAL */
    /*     Limit-Handling: automatically limit Dst-Signal */
    /*     Conversion-Handling: Internal conversion */
    /*     Out-Off-Range-Handling: Cancel conversion if Src-Signal is out of valid range */
    
    /* Copy SRC to temporary-src-container */
    bus_cpy = 0U;
    if(READ_SIGNAL_DATA_API(EduPriv_ACU_EmSpdTgt, &bus_cpy) == READ_SIGNAL_DATA_API_SUCCESS)
    {
        
        /* Conversion of 'EduPriv_ACU_EmSpdTgt' to 'Pl_AcuEmSpdTar' */
        /*lint -save -e734 */
        /*lint -save -e571 */
        sys_cpy0 = (ICS_PL_S16)(((((ICS_PL_S32)bus_cpy) + 1) / 2)-16000);
        /*lint -restore */
        /*lint -restore */
        /* Copy temporary-dst-container to DST */
        SET_Pl_AcuEmSpdTar(sys_cpy0);
    }
    else
    {
        tmp_return_value = ICS_PL_FALSE;
    }
    
    return tmp_return_value;
}
#undef ACTION_ID
#define ACTION_ID ACTION_ID_PL_Cvt_EduPriv_ACU_EmTqCtrlModReq
/*lint  -efile(451,ipl_hook_rx_priv_mcr.h) */
#include <ipl_hook_rx_priv_mcr.h>
#define  MEM_CODE            ICS_PL_MEM_CODE_SERVICE
#include <gmem.h>
/*lint  -efunc(774,PL_Cvt_EduPriv_ACU_EmTqCtrlModReq) */
ICS_PL_RETURN_TYPE PL_Cvt_EduPriv_ACU_EmTqCtrlModReq(void)
{
    /* Conversion for RX-Bus-Signal 'EduPriv_ACU_EmTqCtrlModReq' */
    
    /* Allocate temporary variables */
    ICS_PL_RETURN_TYPE tmp_return_value = ICS_PL_TRUE;
    ICS_PL_FLAG bus_cpy;
    ICS_PL_FLAG sys_cpy0 = ICS_PL_FALSE;
    
    
    /* Source-Signal Description: */
    /*     Name: EduPriv_ACU_EmTqCtrlModReq(intc_sigcv_rx_priv) */
    /*     Category, Type, length, Interface: TEXT, ICS_PL_FLAG, 1 bits, API */
    /*     Desc: Request by ACU to PE for EM torque control mode */
    /*     State(s): [0x0...    ] */
    /*     Text definitions (Name [CLL, CUL]) */
    /*     EM torque control requested [0x1; 0x1] */
    /*     EM torque control not requested [0x0; 0x0] */
    
    /* Destination-Signal Description: */
    /*     Name: Pl_AcuEmTqCtlModReq(intc_sigcv_rx_priv) */
    /*     Category, Type, Interface: TEXT, ICS_PL_FLAG, VAR */
    /*     Desc: Clutch is  requesting to activate torque control */
    /*     Text definitions (Name [CLL, CUL]) */
    /*     FALSE [0x0; 0x0] */
    /*     TRUE [0x1; 0x1] */
    /*     Variable-Name: Pl_AcuEmTqCtlModReq */
    
    /* Mapping Description: */
    /*     ID: intc_sigcv_rx_priv_Mapping00075 */
    /*     Processing: UNCONDITIONAL */
    /*     Text Mapping */
    /*     SRC -> DST */
    /*     EM torque control not requested[0x0] -> FALSE[0x0] */
    /*     EM torque control requested[0x1] -> TRUE[0x1] */
    /*     Limit-Handling: automatically limit Dst-Signal */
    /*     Conversion-Handling: Internal conversion */
    /*     Out-Off-Range-Handling: Cancel conversion if Src-Signal is out of valid range */
    
    /* Copy SRC to temporary-src-container */
    bus_cpy = ICS_PL_FALSE;
    if(READ_SIGNAL_DATA_API(EduPriv_ACU_EmTqCtrlModReq, &bus_cpy) == READ_SIGNAL_DATA_API_SUCCESS)
    {
        
        if(bus_cpy == ICS_PL_FALSE)
        {
            /* Map SRC-Value 'EM torque control not requested' to DST-Value 'FALSE' */
            sys_cpy0 = ICS_PL_FALSE;
        }
        else
        {
            /* Map SRC-Value 'EM torque control requested' to DST-Value 'TRUE' */
            sys_cpy0 = ICS_PL_TRUE;
        }
        /* Copy temporary-dst-container to DST */
        SET_Pl_AcuEmTqCtlModReq(sys_cpy0);
    }
    else
    {
        tmp_return_value = ICS_PL_FALSE;
    }
    
    return tmp_return_value;
}
#undef ACTION_ID
#define ACTION_ID ACTION_ID_PL_Cvt_EduPriv_ACU_EmTqTgt
/*lint  -efile(451,ipl_hook_rx_priv_mcr.h) */
#include <ipl_hook_rx_priv_mcr.h>
#define  MEM_CODE            ICS_PL_MEM_CODE_SERVICE
#include <gmem.h>
/*lint  -efunc(774,PL_Cvt_EduPriv_ACU_EmTqTgt) */
ICS_PL_RETURN_TYPE PL_Cvt_EduPriv_ACU_EmTqTgt(void)
{
    /* Conversion for RX-Bus-Signal 'EduPriv_ACU_EmTqTgt' */
    
    /* Allocate temporary variables */
    ICS_PL_RETURN_TYPE tmp_return_value = ICS_PL_TRUE;
    ICS_PL_U8 bus_cpy;
    ICS_PL_FLOAT sys_cpy0 = 0.0F;
    
    
    /* Source-Signal Description: */
    /*     Name: EduPriv_ACU_EmTqTgt(intc_sigcv_rx_priv) */
    /*     Category, Type, length, Interface: NUM, ICS_PL_U8, 8 bits, API */
    /*     Desc: ACU EM target torque */
    /*     State(s): [0x80...    ] */
    /*     Coded Range: [0x0...0xFF] */
    /*     Harmonized Physical Range: [-64...63.5] [Nm] */
    /*     Original Physical Range: [-64...63.5] [Nm] */
    
    /* Destination-Signal Description: */
    /*     Name: Pl_AcuEmTqTar(intc_sigcv_rx_priv) */
    /*     Category, Type, Interface: NUM, ICS_PL_FLOAT, VAR */
    /*     Desc: Electrical machine torque requested by clutch */
    /*     Harmonized Physical Range: [-1024...1023.96875] [PD_Nm] */
    /*     Original Physical Range: [-1024...1023.96875] [NoUnit] */
    /*     Variable-Name: Pl_AcuEmTqTar */
    
    /* Mapping Description: */
    /*     ID: intc_sigcv_rx_priv_Mapping00076 */
    /*     Processing: UNCONDITIONAL */
    /*     Limit-Handling: automatically limit Dst-Signal */
    /*     Conversion-Handling: Internal conversion */
    /*     Out-Off-Range-Handling: Cancel conversion if Src-Signal is out of valid range */
    
    /* Copy SRC to temporary-src-container */
    bus_cpy = 0U;
    if(READ_SIGNAL_DATA_API(EduPriv_ACU_EmTqTgt, &bus_cpy) == READ_SIGNAL_DATA_API_SUCCESS)
    {
        
        sys_cpy0 = ((ICS_PL_FLOAT)bus_cpy * ((ICS_PL_FLOAT)0.5)) + ((ICS_PL_FLOAT)-64);

        /* Copy temporary-dst-container to DST */
        SET_Pl_AcuEmTqTar(sys_cpy0);
    }
    else
    {
        tmp_return_value = ICS_PL_FALSE;
    }
    
    return tmp_return_value;
}
#undef ACTION_ID
#define ACTION_ID ACTION_ID_PL_Cvt_EduPriv_ACU_OperSt
/*lint  -efile(451,ipl_hook_rx_priv_mcr.h) */
#include <ipl_hook_rx_priv_mcr.h>
#define  MEM_CODE            ICS_PL_MEM_CODE_SERVICE
#include <gmem.h>
/*lint  -efunc(774,PL_Cvt_EduPriv_ACU_OperSt) */
ICS_PL_RETURN_TYPE PL_Cvt_EduPriv_ACU_OperSt(void)
{
    /* Conversion for RX-Bus-Signal 'EduPriv_ACU_OperSt' */
    
    /* Allocate temporary variables */
    ICS_PL_RETURN_TYPE tmp_return_value = ICS_PL_TRUE;
    ICS_PL_U8 bus_cpy;
    ICS_PL_U8 sys_cpy0 = 0U;
    
    
    /* Source-Signal Description: */
    /*     Name: EduPriv_ACU_OperSt(intc_sigcv_rx_priv) */
    /*     Category, Type, length, Interface: TEXT, ICS_PL_U8, 4 bits, API */
    /* Desc: ACU operation state
Further Explanation to Error States:
0xC: Temporarely Unavailable (no */
    /* interference required)
0xD: Unavailable Recoverable (reset by VCU possible)
0xE: Permanently */
    /* Unavailable (CL15 cycle required) */
    /*     State(s): [0x0...    ] */
    /*     Text definitions (Name [CLL, CUL]) */
    /*     Shutdown [0xF; 0xF] */
    /*     Permanently Unavailable [0xE; 0xE] */
    /*     Unavailable Recoverable [0xD; 0xD] */
    /*     Temporarily Unavailable [0xC; 0xC] */
    /*     Calibrating [0xB; 0xB] */
    /*     Calibration Required [0xA; 0xA] */
    /*     Referencing [0x9; 0x9] */
    /*     Referencing Required [0x8; 0x8] */
    /*     Dead Code [0x5; 0x5] */
    /*     Functions Available [0x2; 0x2] */
    /*     Waiting for Switch Test [0x1; 0x1] */
    /*     Initializing [0x0; 0x0] */
    
    /* Destination-Signal Description: */
    /*     Name: Pl_AcuOperSt(intc_sigcv_rx_priv) */
    /*     Category, Type, Interface: TEXT, ICS_PL_U8, VAR */
    /*     Desc: ACU operation status */
    /*     State(s): [0x0...0x0] */
    /*     Text definitions (Name [CLL, CUL]) */
    /*     Init [0x0; 0x0] */
    /*     Referencing [0x1; 0x1] */
    /*     Ready [0x2; 0x2] */
    /*     CAN error [0x3; 0x3] */
    /*     Shift error [0x4; 0x4] */
    /*     Preperation power down [0x5; 0x5] */
    /*     Power down [0x6; 0x6] */
    /*     Variable-Name: Pl_AcuOperSt */
    
    /* Mapping Description: */
    /*     ID: intc_sigcv_rx_priv_Mapping00112 */
    /*     Processing: UNCONDITIONAL */
    /*     Text Mapping */
    /*     SRC -> DST */
    /*     Initializing[0x0] -> Init[0x0] */
    /*     Functions Available[0x2] -> Ready[0x2] */
    /*     Referencing[0x9] -> Referencing[0x1] */
    /*     Shutdown[0xF] -> Power down[0x6] */
    /*     Limit-Handling: automatically limit Dst-Signal */
    /*     Conversion-Handling: Internal conversion */
    /*     Out-Off-Range-Handling: Cancel conversion if Src-Signal is out of valid range */
    
    /* Copy SRC to temporary-src-container */
    bus_cpy = 0U;
    if(READ_SIGNAL_DATA_API(EduPriv_ACU_OperSt, &bus_cpy) == READ_SIGNAL_DATA_API_SUCCESS)
    {
        
        if(bus_cpy == 0U)
        {
            /* Map SRC-Value 'Initializing' to DST-Value 'Init' */
            sys_cpy0 = 0U;
        }
        else if(bus_cpy == 2U)
        {
            /* Map SRC-Value 'Functions Available' to DST-Value 'Ready' */
            sys_cpy0 = 2U;
        }
        else if(bus_cpy == 9U)
        {
            /* Map SRC-Value 'Referencing' to DST-Value 'Referencing' */
            sys_cpy0 = 1U;
        }
        else if(bus_cpy == 15U)
        {
            /* Map SRC-Value 'Shutdown' to DST-Value 'Power down' */
            sys_cpy0 = 6U;
        }
        else
        {
            /* SRC is not within the valid COD-range => cancel processing */
            tmp_return_value = ICS_PL_FALSE;
        }
        if(tmp_return_value == ICS_PL_TRUE)
        {
            /* Copy temporary-dst-container to DST */
            SET_Pl_AcuOperSt(sys_cpy0);
        }
        else
        {
            /* Nothing to do here */
        }
    }
    else
    {
        tmp_return_value = ICS_PL_FALSE;
    }
    
    return tmp_return_value;
}
#undef ACTION_ID
#define ACTION_ID ACTION_ID_PL_Cvt_EduPriv_ACU_TqLimMax
/*lint  -efile(451,ipl_hook_rx_priv_mcr.h) */
#include <ipl_hook_rx_priv_mcr.h>
#define  MEM_CODE            ICS_PL_MEM_CODE_SERVICE
#include <gmem.h>
/*lint  -efunc(774,PL_Cvt_EduPriv_ACU_TqLimMax) */
ICS_PL_RETURN_TYPE PL_Cvt_EduPriv_ACU_TqLimMax(void)
{
    /* Conversion for RX-Bus-Signal 'EduPriv_ACU_TqLimMax' */
    
    /* Allocate temporary variables */
    ICS_PL_RETURN_TYPE tmp_return_value = ICS_PL_TRUE;
    ICS_PL_U8 bus_cpy;
    ICS_PL_FLOAT sys_cpy0 = 0.0F;
    
    
    /* Source-Signal Description: */
    /*     Name: EduPriv_ACU_TqLimMax(intc_sigcv_rx_priv) */
    /*     Category, Type, length, Interface: NUM, ICS_PL_U8, 8 bits, API */
    /*     Desc: Max. traction motor torque limit requested by ACU */
    /*     State(s): [0x0...    ] */
    /*     Coded Range: [0x0...0xFF] */
    /*     Harmonized Physical Range: [0...510] [Nm] */
    /*     Original Physical Range: [0...510] [Nm] */
    
    /* Destination-Signal Description: */
    /*     Name: Pl_AcuTqLimMax(intc_sigcv_rx_priv) */
    /*     Category, Type, Interface: NUM, ICS_PL_FLOAT, VAR */
    /*     Desc: Maximum electrical machine torque requested by clutch */
    /*     Harmonized Physical Range: [-1024...1023.96875] [PD_Nm] */
    /*     Original Physical Range: [-1024...1023.96875] [Nm] */
    /*     Variable-Name: Pl_AcuTqLimMax */
    
    /* Mapping Description: */
    /*     ID: intc_sigcv_rx_priv_Mapping00077 */
    /*     Processing: UNCONDITIONAL */
    /*     Limit-Handling: automatically limit Dst-Signal */
    /*     Conversion-Handling: Internal conversion */
    /*     Out-Off-Range-Handling: Cancel conversion if Src-Signal is out of valid range */
    
    /* Copy SRC to temporary-src-container */
    bus_cpy = 0U;
    if(READ_SIGNAL_DATA_API(EduPriv_ACU_TqLimMax, &bus_cpy) == READ_SIGNAL_DATA_API_SUCCESS)
    {
        
        sys_cpy0 = ((ICS_PL_FLOAT)bus_cpy * (ICS_PL_FLOAT)2);

        /* Copy temporary-dst-container to DST */
        SET_Pl_AcuTqLimMax(sys_cpy0);
    }
    else
    {
        tmp_return_value = ICS_PL_FALSE;
    }
    
    return tmp_return_value;
}
#undef ACTION_ID
#define ACTION_ID ACTION_ID_PL_Cvt_EduPriv_ACU_TqLimMin
/*lint  -efile(451,ipl_hook_rx_priv_mcr.h) */
#include <ipl_hook_rx_priv_mcr.h>
#define  MEM_CODE            ICS_PL_MEM_CODE_SERVICE
#include <gmem.h>
/*lint  -efunc(774,PL_Cvt_EduPriv_ACU_TqLimMin) */
ICS_PL_RETURN_TYPE PL_Cvt_EduPriv_ACU_TqLimMin(void)
{
    /* Conversion for RX-Bus-Signal 'EduPriv_ACU_TqLimMin' */
    
    /* Allocate temporary variables */
    ICS_PL_RETURN_TYPE tmp_return_value = ICS_PL_TRUE;
    ICS_PL_U8 bus_cpy;
    ICS_PL_FLOAT sys_cpy0 = 0.0F;
    
    
    /* Source-Signal Description: */
    /*     Name: EduPriv_ACU_TqLimMin(intc_sigcv_rx_priv) */
    /*     Category, Type, length, Interface: NUM, ICS_PL_U8, 8 bits, API */
    /*     Desc: Min. traction motor torque limit requested by ACU */
    /*     State(s): [0xFF...    ] */
    /*     Coded Range: [0x0...0xFF] */
    /*     Harmonized Physical Range: [-510...0] [Nm] */
    /*     Original Physical Range: [-510...0] [Nm] */
    
    /* Destination-Signal Description: */
    /*     Name: Pl_AcuTqLimMin(intc_sigcv_rx_priv) */
    /*     Category, Type, Interface: NUM, ICS_PL_FLOAT, VAR */
    /*     Desc: Minimum electrical machine torque requested by clutch */
    /*     Harmonized Physical Range: [-1024...1023.96875] [PD_Nm] */
    /*     Original Physical Range: [-1024...1023.96875] [Nm] */
    /*     Variable-Name: Pl_AcuTqLimMin */
    
    /* Mapping Description: */
    /*     ID: intc_sigcv_rx_priv_Mapping00078 */
    /*     Processing: UNCONDITIONAL */
    /*     Limit-Handling: automatically limit Dst-Signal */
    /*     Conversion-Handling: Internal conversion */
    /*     Out-Off-Range-Handling: Cancel conversion if Src-Signal is out of valid range */
    
    /* Copy SRC to temporary-src-container */
    bus_cpy = 0U;
    if(READ_SIGNAL_DATA_API(EduPriv_ACU_TqLimMin, &bus_cpy) == READ_SIGNAL_DATA_API_SUCCESS)
    {
        
        sys_cpy0 = ((ICS_PL_FLOAT)bus_cpy * ((ICS_PL_FLOAT)2)) + ((ICS_PL_FLOAT)-510);

        /* Copy temporary-dst-container to DST */
        SET_Pl_AcuTqLimMin(sys_cpy0);
    }
    else
    {
        tmp_return_value = ICS_PL_FALSE;
    }
    
    return tmp_return_value;
}
#undef ACTION_ID
#define ACTION_ID ACTION_ID_PL_Cvt_EduPriv_ACU_TqLimReq
/*lint  -efile(451,ipl_hook_rx_priv_mcr.h) */
#include <ipl_hook_rx_priv_mcr.h>
#define  MEM_CODE            ICS_PL_MEM_CODE_SERVICE
#include <gmem.h>
/*lint  -efunc(774,PL_Cvt_EduPriv_ACU_TqLimReq) */
ICS_PL_RETURN_TYPE PL_Cvt_EduPriv_ACU_TqLimReq(void)
{
    /* Conversion for RX-Bus-Signal 'EduPriv_ACU_TqLimReq' */
    
    /* Allocate temporary variables */
    ICS_PL_RETURN_TYPE tmp_return_value = ICS_PL_TRUE;
    ICS_PL_FLAG bus_cpy;
    ICS_PL_U8 sys_cpy0 = 0U;
    
    
    /* Source-Signal Description: */
    /*     Name: EduPriv_ACU_TqLimReq(intc_sigcv_rx_priv) */
    /*     Category, Type, length, Interface: TEXT, ICS_PL_FLAG, 1 bits, API */
    /*     Desc: ACU torque limit request (activation of requested torque limits) */
    /*     State(s): [0x0...    ] */
    /*     Text definitions (Name [CLL, CUL]) */
    /*     Torque limitation active [0x1; 0x1] */
    /*     Torque limitation inactive [0x0; 0x0] */
    
    /* Destination-Signal Description: */
    /*     Name: Pl_AcuTqLimReq(intc_sigcv_rx_priv) */
    /*     Category, Type, Interface: TEXT, ICS_PL_U8, VAR */
    /*     Desc: State of electric machine torque limitation selection according to ACU control */
    /*     Text definitions (Name [CLL, CUL]) */
    /*     EXT [0x0; 0x0] */
    /*     CLU [0x1; 0x1] */
    /*     Variable-Name: Pl_AcuTqLimReq */
    
    /* Mapping Description: */
    /*     ID: intc_sigcv_rx_priv_Mapping00079 */
    /*     Processing: UNCONDITIONAL */
    /*     Text Mapping */
    /*     SRC -> DST */
    /*     Torque limitation inactive[0x0] -> EXT[0x0] */
    /*     Torque limitation active[0x1] -> CLU[0x1] */
    /*     Limit-Handling: automatically limit Dst-Signal */
    /*     Conversion-Handling: Internal conversion */
    /*     Out-Off-Range-Handling: Cancel conversion if Src-Signal is out of valid range */
    
    /* Copy SRC to temporary-src-container */
    bus_cpy = ICS_PL_FALSE;
    if(READ_SIGNAL_DATA_API(EduPriv_ACU_TqLimReq, &bus_cpy) == READ_SIGNAL_DATA_API_SUCCESS)
    {
        
        if(bus_cpy == ICS_PL_FALSE)
        {
            /* Map SRC-Value 'Torque limitation inactive' to DST-Value 'EXT' */
            sys_cpy0 = 0U;
        }
        else
        {
            /* Map SRC-Value 'Torque limitation active' to DST-Value 'CLU' */
            sys_cpy0 = 1U;
        }
        /* Copy temporary-dst-container to DST */
        SET_Pl_AcuTqLimReq(sys_cpy0);
    }
    else
    {
        tmp_return_value = ICS_PL_FALSE;
    }
    
    return tmp_return_value;
}
