/****************************************************************************
 * COPYRIGHT VITESCO TECHNOLOGIES GROUP AG (EXCLUSIVE RIGHTS) 
 * Confidential
 * 
 * The reproduction, transmission or use of this document or its
 * contents is not permitted without express written authority.
 * Offenders will be liable for damages. All rights, including rights
 * created by patent grant or registration of a utility model or design,
 * are reserved.
 *---------------------------------------------------------------------------
 * 
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 * !!! This file is generated by Signal Mapper (SIMA) Code-Generator !!!
 * !!! Do NOT modify this file manually                            !!!
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 * 
 * Purpose:    PL Hook Header for MCR
 * 
 * Processor:  independent
 * Tool chain: 
 *    CG-Version:        6.2.0
 *    Schema-Version:    1.18.0
 *    Generation-Date:   29.08.2024  16:51:03  
 *    Generated by user: uiv00534
 * Filename:   $Workfile$
 * Revision:   $Revision: 1.1 $
 * Author:     $Author: Zhang Yi (uiv00534) (uiv00534) $
 * Date:       $Date: 2024/09/03 03:13:03CEST $
 * Changes:    $Log: ipl_hook_rx_priv_mcr.h  $
 * Changes:    Revision 1.1 2024/09/03 03:13:03CEST Zhang Yi (uiv00534) (uiv00534) 
 * Changes:    Initial revision
 * Changes:    Member added to project /ES/FS/0G/H0D/0A/bsw/intc/intc_sigcv_cclu1/i/project.pj
 * 
****************************************************************************/
#ifndef IPL_HOOK_RX_PRIV_MCR_H
#define IPL_HOOK_RX_PRIV_MCR_H

#undef ACTION_ID_NONE
#undef RUNNABLE_ID_NONE
#define ACTION_ID_NONE 0
#define RUNNABLE_ID_NONE 0

#define ACTION_ID_PL_Cvt_EduPriv_ACU_ConSt 3
#define ACTION_ID_PL_Cvt_EduPriv_ACU_EmSpdCtrlModReq 4
#define ACTION_ID_PL_Cvt_EduPriv_ACU_EmSpdTgt 5
#define ACTION_ID_PL_Cvt_EduPriv_ACU_EmTqCtrlModReq 6
#define ACTION_ID_PL_Cvt_EduPriv_ACU_EmTqTgt 7
#define ACTION_ID_PL_Cvt_EduPriv_ACU_OperSt 8
#define ACTION_ID_PL_Cvt_EduPriv_ACU_TqLimMax 9
#define ACTION_ID_PL_Cvt_EduPriv_ACU_TqLimMin 10
#define ACTION_ID_PL_Cvt_EduPriv_ACU_TqLimReq 11
#endif

#if !(defined RUNNABLE_ID || defined ACTION_ID)
#error "No RUNNABLE_ID or ACTION_ID defined"
#endif
#ifndef RUNNABLE_ID
#define RUNNABLE_ID RUNNABLE_ID_NONE
#endif
#ifndef ACTION_ID
#define ACTION_ID ACTION_ID_NONE
#endif


/* Getters and setters for everyone */
#ifndef SET_Pl_AcuConnectionSt
  #define SET_Pl_AcuConnectionSt(x) (Pl_AcuConnectionSt=(x))
#endif
#ifndef SET_Pl_AcuEmSpdCtlModReq
  #define SET_Pl_AcuEmSpdCtlModReq(x) (Pl_AcuEmSpdCtlModReq=(x))
#endif
#ifndef SET_Pl_AcuEmSpdTar
  #define SET_Pl_AcuEmSpdTar(x) (Pl_AcuEmSpdTar=(x))
#endif
#ifndef SET_Pl_AcuEmTqCtlModReq
  #define SET_Pl_AcuEmTqCtlModReq(x) (Pl_AcuEmTqCtlModReq=(x))
#endif
#ifndef SET_Pl_AcuEmTqTar
  #define SET_Pl_AcuEmTqTar(x) (Pl_AcuEmTqTar=(x))
#endif
#ifndef SET_Pl_AcuOperSt
  #define SET_Pl_AcuOperSt(x) (Pl_AcuOperSt=(x))
#endif
#ifndef SET_Pl_AcuTqLimMax
  #define SET_Pl_AcuTqLimMax(x) (Pl_AcuTqLimMax=(x))
#endif
#ifndef SET_Pl_AcuTqLimMin
  #define SET_Pl_AcuTqLimMin(x) (Pl_AcuTqLimMin=(x))
#endif
#ifndef SET_Pl_AcuTqLimReq
  #define SET_Pl_AcuTqLimReq(x) (Pl_AcuTqLimReq=(x))
#endif

#undef RUNNABLE_ID
#define RUNNABLE_ID RUNNABLE_ID_NONE
#undef ACTION_ID
#define ACTION_ID ACTION_ID_NONE

#if !((RUNNABLE_ID == RUNNABLE_ID_NONE) && (ACTION_ID == RUNNABLE_ID_NONE))
#error "Illegal RUNNABLE_ID or ACTION_ID found"
#endif


