/****************************************************************************
 * COPYRIGHT VITESCO TECHNOLOGIES GROUP AG (EXCLUSIVE RIGHTS) 
 * Confidential
 * 
 * The reproduction, transmission or use of this document or its
 * contents is not permitted without express written authority.
 * Offenders will be liable for damages. All rights, including rights
 * created by patent grant or registration of a utility model or design,
 * are reserved.
 *---------------------------------------------------------------------------
 * 
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 * !!! This file is generated by Signal Mapper (SIMA) Code-Generator !!!
 * !!! Do NOT modify this file manually                            !!!
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 * 
 * Purpose:    PL Hook Header for data H File
 * 
 * Processor:  independent
 * Tool chain: 
 *    CG-Version:        6.2.0
 *    Schema-Version:    1.18.0
 *    Generation-Date:   29.08.2024  16:51:03  
 *    Generated by user: uiv00534
 * Filename:   $Workfile$
 * Revision:   $Revision: 1.2 $
 * Author:     $Author: Zhang Yi (uiv00534) (uiv00534) $
 * Date:       $Date: 2024/09/06 07:27:51CEST $
 * Changes:    $Log: ipl_hook_tx_priv_data.h  $
 * Changes:    Revision 1.2 2024/09/06 07:27:51CEST Zhang Yi (uiv00534) (uiv00534) 
 * Changes:    16683028: intc_sigcv_cclu1: doc development and code update
 * Changes:    Revision 1.1 2024/09/03 03:13:05CEST Zhang Yi (uiv00534) (uiv00534) 
 * Changes:    Initial revision
 * Changes:    Member added to project /ES/FS/0G/H0D/0A/bsw/intc/intc_sigcv_cclu1/i/project.pj
 * 
****************************************************************************/
#ifndef IPL_HOOK_TX_PRIV_DATA_H
#define IPL_HOOK_TX_PRIV_DATA_H



/* System-Variable declaration for Pl_PeConCmd */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_8
#include <gmem.h>
extern ICS_PL_U8 Pl_PeConCmd;

/* System-Variable declaration for Pl_PeEmTq */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
extern ICS_PL_FLOAT Pl_PeEmTq;

/* System-Variable declaration for Pl_PeSpdCtlCfm */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_8
#include <gmem.h>
extern ICS_PL_U8 Pl_PeSpdCtlCfm;

/* System-Variable declaration for Pl_PeTqCtlCfm */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_8
#include <gmem.h>
extern ICS_PL_U8 Pl_PeTqCtlCfm;

/* System-Variable declaration for Pl_WhlSpdMeasd1 */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
extern ICS_PL_FLOAT Pl_WhlSpdMeasd1;

/* System-Variable declaration for Pl_WhlSpdMeasd2 */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
extern ICS_PL_FLOAT Pl_WhlSpdMeasd2;

/* System-Variable declaration for Pl_WhlSpdMeasdVld1 */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_8
#include <gmem.h>
extern ICS_PL_U8 Pl_WhlSpdMeasdVld1;

/* System-Variable declaration for Pl_WhlSpdMeasdVld2 */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_8
#include <gmem.h>
extern ICS_PL_U8 Pl_WhlSpdMeasdVld2;

/* System-Variable declaration for Pl_TSemcdPwrSwiDiodeInvtMax */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
extern ICS_PL_FLOAT Pl_TSemcdPwrSwiDiodeInvtMax;

/* System-Variable declaration for Pl_TSemcdDiodeInvtMax */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
extern ICS_PL_FLOAT Pl_TSemcdDiodeInvtMax;

/* System-Variable declaration for Pl_TWtrCoolIn */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_16
#include <gmem.h>
extern ICS_PL_U16 Pl_TWtrCoolIn;

/* System-Variable declaration for Pl_StEmInvtReq */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_16
#include <gmem.h>
extern ICS_PL_U16 Pl_StEmInvtReq;

/* System-Variable declaration for Pl_FacMduInvtFil */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
extern ICS_PL_FLOAT Pl_FacMduInvtFil;

/* System-Variable declaration for Pl_TypPwmInvtOppReq */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_8
#include <gmem.h>
extern ICS_PL_U8 Pl_TypPwmInvtOppReq;

/* System-Variable declaration for Pl_IRmsPha3FilInvt */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
extern ICS_PL_FLOAT Pl_IRmsPha3FilInvt;

/* System-Variable declaration for Pl_FacPwrInvtFil */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
extern ICS_PL_FLOAT Pl_FacPwrInvtFil;

/* System-Variable declaration for Pl_StQlyTqEmEstim */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_8
#include <gmem.h>
extern ICS_PL_U8 Pl_StQlyTqEmEstim;


#include <gmem.h>
#endif
