/****************************************************************************
 * COPYRIGHT VITESCO TECHNOLOGIES GROUP AG (EXCLUSIVE RIGHTS) 
 * Confidential
 * 
 * The reproduction, transmission or use of this document or its
 * contents is not permitted without express written authority.
 * Offenders will be liable for damages. All rights, including rights
 * created by patent grant or registration of a utility model or design,
 * are reserved.
 *---------------------------------------------------------------------------
 * 
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 * !!! This file is generated by Signal Mapper (SIMA) Code-Generator !!!
 * !!! Do NOT modify this file manually                            !!!
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 * 
 * Purpose:    PL Hook Header for data H File
 * 
 * Processor:  independent
 * Tool chain: 
 *    CG-Version:        6.2.0
 *    Schema-Version:    1.18.0
 *    Generation-Date:   29.08.2024  16:51:03  
 *    Generated by user: uiv00534
 * Filename:   $Workfile$
 * Revision:   $Revision: 1.1 $
 * Author:     $Author: Zhang Yi (uiv00534) (uiv00534) $
 * Date:       $Date: 2024/09/03 03:13:02CEST $
 * Changes:    $Log: ipl_hook_rx_priv_data.h  $
 * Changes:    Revision 1.1 2024/09/03 03:13:02CEST Zhang Yi (uiv00534) (uiv00534) 
 * Changes:    Initial revision
 * Changes:    Member added to project /ES/FS/0G/H0D/0A/bsw/intc/intc_sigcv_cclu1/i/project.pj
 * 
****************************************************************************/
#ifndef IPL_HOOK_RX_PRIV_DATA_H
#define IPL_HOOK_RX_PRIV_DATA_H



/* System-Variable declaration for Pl_AcuConnectionSt */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_8
#include <gmem.h>
extern ICS_PL_U8 Pl_AcuConnectionSt;
/* System-Variable declaration for Pl_AcuEmSpdCtlModReq */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_8
#include <gmem.h>
extern ICS_PL_FLAG Pl_AcuEmSpdCtlModReq;
/* System-Variable declaration for Pl_AcuEmSpdTar */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
extern ICS_PL_S16 Pl_AcuEmSpdTar;
/* System-Variable declaration for Pl_AcuEmTqCtlModReq */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_8
#include <gmem.h>
extern ICS_PL_FLAG Pl_AcuEmTqCtlModReq;
/* System-Variable declaration for Pl_AcuEmTqTar */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
extern ICS_PL_FLOAT Pl_AcuEmTqTar;
/* System-Variable declaration for Pl_AcuOperSt */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_8
#include <gmem.h>
extern ICS_PL_U8 Pl_AcuOperSt;
/* System-Variable declaration for Pl_AcuTqLimMax */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
extern ICS_PL_FLOAT Pl_AcuTqLimMax;
/* System-Variable declaration for Pl_AcuTqLimMin */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
extern ICS_PL_FLOAT Pl_AcuTqLimMin;
/* System-Variable declaration for Pl_AcuTqLimReq */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_8
#include <gmem.h>
extern ICS_PL_U8 Pl_AcuTqLimReq;


#include <gmem.h>
#endif
