/****************************************************************************
 * COPYRIGHT VITESCO TECHNOLOGIES GROUP AG (EXCLUSIVE RIGHTS) 
 * Confidential
 * 
 * The reproduction, transmission or use of this document or its
 * contents is not permitted without express written authority.
 * Offenders will be liable for damages. All rights, including rights
 * created by patent grant or registration of a utility model or design,
 * are reserved.
 *---------------------------------------------------------------------------
 * 
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 * !!! This file is generated by Signal Mapper (SIMA) Code-Generator !!!
 * !!! Do NOT modify this file manually                            !!!
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 * 
 * Purpose:    PL Hook Header for data C Files
 * 
 * Processor:  independent
 * Tool chain: 
 *    CG-Version:        6.2.0
 *    Schema-Version:    1.18.0
 *    Generation-Date:   29.08.2024  16:51:03  
 *    Generated by user: uiv00534
 * Filename:   $Workfile$
 * Revision:   $Revision: 1.2 $
 * Author:     $Author: Zhang Yi (uiv00534) (uiv00534) $
 * Date:       $Date: 2024/09/06 07:27:52CEST $
 * Changes:    $Log: ipl_hook_tx_priv_data.c  $
 * Changes:    Revision 1.2 2024/09/06 07:27:52CEST Zhang Yi (uiv00534) (uiv00534) 
 * Changes:    16683028: intc_sigcv_cclu1: doc development and code update
 * Changes:    Revision 1.1 2024/09/03 03:13:04CEST Zhang Yi (uiv00534) (uiv00534) 
 * Changes:    Initial revision
 * Changes:    Member added to project /ES/FS/0G/H0D/0A/bsw/intc/intc_sigcv_cclu1/i/project.pj
 * 
****************************************************************************/
/*lint -esym(750,IPL_HOOK_TX_PRIV_DATA_C) */
#define IPL_HOOK_TX_PRIV_DATA_C
#include <intc_sigcv_cclu1_im.h>




/* System-Variable definition */
#define MEM_DATA MEM_DATA_PUBLIC_8
#include <gmem.h>
ICS_PL_U8 Pl_PeConCmd;


/* System-Variable definition */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
ICS_PL_FLOAT Pl_PeEmTq;


/* System-Variable definition */
#define MEM_DATA MEM_DATA_PUBLIC_8
#include <gmem.h>
ICS_PL_U8 Pl_PeSpdCtlCfm;


/* System-Variable definition */
#define MEM_DATA MEM_DATA_PUBLIC_8
#include <gmem.h>
ICS_PL_U8 Pl_PeTqCtlCfm;


/* System-Variable definition */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
ICS_PL_FLOAT Pl_WhlSpdMeasd1;


/* System-Variable definition */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
ICS_PL_FLOAT Pl_WhlSpdMeasd2;


/* System-Variable definition */
#define MEM_DATA MEM_DATA_PUBLIC_8
#include <gmem.h>
ICS_PL_U8 Pl_WhlSpdMeasdVld1;


/* System-Variable definition */
#define MEM_DATA MEM_DATA_PUBLIC_8
#include <gmem.h>
ICS_PL_U8 Pl_WhlSpdMeasdVld2;


/* System-Variable definition */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
ICS_PL_FLOAT Pl_TSemcdPwrSwiDiodeInvtMax;


/* System-Variable definition */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
ICS_PL_FLOAT Pl_TSemcdDiodeInvtMax;


/* System-Variable definition */
#define MEM_DATA MEM_DATA_PUBLIC_16
#include <gmem.h>
ICS_PL_U16 Pl_TWtrCoolIn;


/* System-Variable definition */
#define MEM_DATA MEM_DATA_PUBLIC_16
#include <gmem.h>
ICS_PL_U16 Pl_StEmInvtReq;


/* System-Variable definition */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
ICS_PL_FLOAT Pl_FacMduInvtFil;


/* System-Variable definition */
#define MEM_DATA MEM_DATA_PUBLIC_8
#include <gmem.h>
ICS_PL_U8 Pl_TypPwmInvtOppReq;


/* System-Variable definition */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
ICS_PL_FLOAT Pl_IRmsPha3FilInvt;


/* System-Variable definition */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
ICS_PL_FLOAT Pl_FacPwrInvtFil;


/* System-Variable definition */
#define MEM_DATA MEM_DATA_PUBLIC_8
#include <gmem.h>
ICS_PL_U8 Pl_StQlyTqEmEstim;
