/****************************************************************************
 * COPYRIGHT VITESCO TECHNOLOGIES GROUP AG (EXCLUSIVE RIGHTS) 
 * Confidential
 * 
 * The reproduction, transmission or use of this document or its
 * contents is not permitted without express written authority.
 * Offenders will be liable for damages. All rights, including rights
 * created by patent grant or registration of a utility model or design,
 * are reserved.
 *---------------------------------------------------------------------------
 * 
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 * !!! This file is generated by Signal Mapper (SIMA) Code-Generator !!!
 * !!! Do NOT modify this file manually                            !!!
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 * 
 * Purpose:    PL Hook Header
 * 
 * Processor:  independent
 * Tool chain: 
 *    CG-Version:        6.2.0
 *    Schema-Version:    1.18.0
 *    Generation-Date:   05.09.2024  16:24:52  
 *    Generated by user: uiv00534
 * Filename:   $Workfile$
 * Revision:   $Revision: 1.2 $
 * Author:     $Author: Zhang Yi (uiv00534) (uiv00534) $
 * Date:       $Date: 2024/09/06 07:27:50CEST $
 * Changes:    $Log: ipl_hook_tx_priv.h  $
 * Changes:    Revision 1.2 2024/09/06 07:27:50CEST Zhang Yi (uiv00534) (uiv00534) 
 * Changes:    16683028: intc_sigcv_cclu1: doc development and code update
 * 
****************************************************************************/
#ifndef IPL_HOOK_TX_PRIV_H
#define IPL_HOOK_TX_PRIV_H

#include <ipl_pcnf.h>


/* Variant-IDs */
#ifndef PrivateCAN
  #define PrivateCAN 1U
#endif


#define  MEM_CODE            ICS_PL_MEM_CODE_SERVICE
#include <gmem.h>


/* PL2Com Definition for EduPriv_PE_ConCmd */
#define PL2COM_DEF_PL_CVT_EDUPRIV_PE_CONCMD
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduPriv_PE_ConCmd(void);
/* PL2Com Definition for EduPriv_PE_CosPhi */
#define PL2COM_DEF_PL_CVT_EDUPRIV_PE_COSPHI
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduPriv_PE_CosPhi(void);
/* PL2Com Definition for EduPriv_PE_DiodeTemperature */
#define PL2COM_DEF_PL_CVT_EDUPRIV_PE_DIODETEMPERATURE
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduPriv_PE_DiodeTemperature(void);
/* PL2Com Definition for EduPriv_PE_EmRotAg */
#define PL2COM_DEF_PL_CVT_EDUPRIV_PE_EMROTAG
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduPriv_PE_EmRotAg(void);
/* PL2Com Definition for EduPriv_PE_EmRotAgVld */
#define PL2COM_DEF_PL_CVT_EDUPRIV_PE_EMROTAGVLD
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduPriv_PE_EmRotAgVld(void);
/* PL2Com Definition for EduPriv_PE_EmSpd */
#define PL2COM_DEF_PL_CVT_EDUPRIV_PE_EMSPD
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduPriv_PE_EmSpd(void);
/* PL2Com Definition for EduPriv_PE_EmSpdVld */
#define PL2COM_DEF_PL_CVT_EDUPRIV_PE_EMSPDVLD
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduPriv_PE_EmSpdVld(void);
/* PL2Com Definition for EduPriv_PE_EmTq */
#define PL2COM_DEF_PL_CVT_EDUPRIV_PE_EMTQ
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduPriv_PE_EmTq(void);
/* PL2Com Definition for EduPriv_PE_EmTqVld */
#define PL2COM_DEF_PL_CVT_EDUPRIV_PE_EMTQVLD
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduPriv_PE_EmTqVld(void);
/* PL2Com Definition for EduPriv_PE_ModulationFactor */
#define PL2COM_DEF_PL_CVT_EDUPRIV_PE_MODULATIONFACTOR
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduPriv_PE_ModulationFactor(void);
/* PL2Com Definition for EduPriv_PE_ModulationProcess */
#define PL2COM_DEF_PL_CVT_EDUPRIV_PE_MODULATIONPROCESS
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduPriv_PE_ModulationProcess(void);
/* PL2Com Definition for EduPriv_PE_NmAcvnAcu */
#define PL2COM_DEF_PL_CVT_EDUPRIV_PE_NMACVNACU
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduPriv_PE_NmAcvnAcu(void);
/* PL2Com Definition for EduPriv_PE_PWMFrequency */
#define PL2COM_DEF_PL_CVT_EDUPRIV_PE_PWMFREQUENCY
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduPriv_PE_PWMFrequency(void);
/* PL2Com Definition for EduPriv_PE_PhaseCurrent */
#define PL2COM_DEF_PL_CVT_EDUPRIV_PE_PHASECURRENT
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduPriv_PE_PhaseCurrent(void);
/* PL2Com Definition for EduPriv_PE_SpdCtrlCfmd */
#define PL2COM_DEF_PL_CVT_EDUPRIV_PE_SPDCTRLCFMD
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduPriv_PE_SpdCtrlCfmd(void);
/* PL2Com Definition for EduPriv_PE_StateInv */
#define PL2COM_DEF_PL_CVT_EDUPRIV_PE_STATEINV
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduPriv_PE_StateInv(void);
/* PL2Com Definition for EduPriv_PE_TjunctionTemperature */
#define PL2COM_DEF_PL_CVT_EDUPRIV_PE_TJUNCTIONTEMPERATURE
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduPriv_PE_TjunctionTemperature(void);
/* PL2Com Definition for EduPriv_PE_TqCtrlCfmd */
#define PL2COM_DEF_PL_CVT_EDUPRIV_PE_TQCTRLCFMD
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduPriv_PE_TqCtrlCfmd(void);
/* PL2Com Definition for EduPriv_PE_WaterTemperature */
#define PL2COM_DEF_PL_CVT_EDUPRIV_PE_WATERTEMPERATURE
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduPriv_PE_WaterTemperature(void);
/* PL2Com Definition for EduPriv_PE_WhlSpd1 */
#define PL2COM_DEF_PL_CVT_EDUPRIV_PE_WHLSPD1
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduPriv_PE_WhlSpd1(void);
/* PL2Com Definition for EduPriv_PE_WhlSpd2 */
#define PL2COM_DEF_PL_CVT_EDUPRIV_PE_WHLSPD2
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduPriv_PE_WhlSpd2(void);
/* PL2Com Definition for EduPriv_PE_WhlSpdVld1 */
#define PL2COM_DEF_PL_CVT_EDUPRIV_PE_WHLSPDVLD1
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduPriv_PE_WhlSpdVld1(void);
/* PL2Com Definition for EduPriv_PE_WhlSpdVld2 */
#define PL2COM_DEF_PL_CVT_EDUPRIV_PE_WHLSPDVLD2
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduPriv_PE_WhlSpdVld2(void);
/* PL2Com Definition for EduPriv_PE_aeIdfLstActErrFmyMon0 */
#define PL2COM_DEF_PL_CVT_EDUPRIV_PE_AEIDFLSTACTERRFMYMON0
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduPriv_PE_aeIdfLstActErrFmyMon0(void);
/* PL2Com Definition for EduPriv_PE_aeIdfLstActErrFmyMon1 */
#define PL2COM_DEF_PL_CVT_EDUPRIV_PE_AEIDFLSTACTERRFMYMON1
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduPriv_PE_aeIdfLstActErrFmyMon1(void);
/* PL2Com Definition for EduPriv_PE_aeIdfLstActErrFmyMon2 */
#define PL2COM_DEF_PL_CVT_EDUPRIV_PE_AEIDFLSTACTERRFMYMON2
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduPriv_PE_aeIdfLstActErrFmyMon2(void);
/* PL2Com Definition for EduPriv_PE_aeIdfLstActErrFmyMon3 */
#define PL2COM_DEF_PL_CVT_EDUPRIV_PE_AEIDFLSTACTERRFMYMON3
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduPriv_PE_aeIdfLstActErrFmyMon3(void);
/* PL2Com Definition for EduPriv_PE_aeIdfLstActErrFmyMon4 */
#define PL2COM_DEF_PL_CVT_EDUPRIV_PE_AEIDFLSTACTERRFMYMON4
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduPriv_PE_aeIdfLstActErrFmyMon4(void);
/* PL2Com Definition for EduPriv_PE_aeIdfLstActErrFmyMon5 */
#define PL2COM_DEF_PL_CVT_EDUPRIV_PE_AEIDFLSTACTERRFMYMON5
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduPriv_PE_aeIdfLstActErrFmyMon5(void);
/* PL2Com Definition for EduPriv_PE_aeIdfLstActErrFmyMon6 */
#define PL2COM_DEF_PL_CVT_EDUPRIV_PE_AEIDFLSTACTERRFMYMON6
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduPriv_PE_aeIdfLstActErrFmyMon6(void);
/* PL2Com Definition for EduPriv_PE_aeIdfLstActErrFmyMon7 */
#define PL2COM_DEF_PL_CVT_EDUPRIV_PE_AEIDFLSTACTERRFMYMON7
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduPriv_PE_aeIdfLstActErrFmyMon7(void);
#include <gmem.h>
#endif
