/****************************************************************************
 * COPYRIGHT VITESCO TECHNOLOGIES GROUP AG (EXCLUSIVE RIGHTS) 
 * Confidential
 * 
 * The reproduction, transmission or use of this document or its
 * contents is not permitted without express written authority.
 * Offenders will be liable for damages. All rights, including rights
 * created by patent grant or registration of a utility model or design,
 * are reserved.
 *---------------------------------------------------------------------------
 * 
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 * !!! This file is generated by Signal Mapper (SIMA) Code-Generator !!!
 * !!! Do NOT modify this file manually                            !!!
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 * 
 * Purpose:    PL Hook Header
 * 
 * Processor:  independent
 * Tool chain: 
 *    CG-Version:        6.2.0
 *    Schema-Version:    1.18.0
 *    Generation-Date:   29.08.2024  16:51:03  
 *    Generated by user: uiv00534
 * Filename:   $Workfile$
 * Revision:   $Revision: 1.1 $
 * Author:     $Author: Zhang Yi (uiv00534) (uiv00534) $
 * Date:       $Date: 2024/09/03 03:13:04CEST $
 * Changes:    $Log: ipl_hook_rx_priv.h  $
 * Changes:    Revision 1.1 2024/09/03 03:13:04CEST Zhang Yi (uiv00534) (uiv00534) 
 * Changes:    Initial revision
 * Changes:    Member added to project /ES/FS/0G/H0D/0A/bsw/intc/intc_sigcv_cclu1/i/project.pj
 * 
****************************************************************************/
#ifndef IPL_HOOK_RX_PRIV_H
#define IPL_HOOK_RX_PRIV_H

#include <ipl_pcnf.h>


/* Variant-IDs */
#ifndef BSample
  #define BSample 1U
#endif


#define  MEM_CODE            ICS_PL_MEM_CODE_SERVICE
#include <gmem.h>


/* PL2Com Definition for EduPriv_ACU_ConSt */
#define PL2COM_DEF_PL_CVT_EDUPRIV_ACU_CONST
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduPriv_ACU_ConSt(void);
/* PL2Com Definition for EduPriv_ACU_EmSpdCtrlModReq */
#define PL2COM_DEF_PL_CVT_EDUPRIV_ACU_EMSPDCTRLMODREQ
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduPriv_ACU_EmSpdCtrlModReq(void);
/* PL2Com Definition for EduPriv_ACU_EmSpdTgt */
#define PL2COM_DEF_PL_CVT_EDUPRIV_ACU_EMSPDTGT
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduPriv_ACU_EmSpdTgt(void);
/* PL2Com Definition for EduPriv_ACU_EmTqCtrlModReq */
#define PL2COM_DEF_PL_CVT_EDUPRIV_ACU_EMTQCTRLMODREQ
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduPriv_ACU_EmTqCtrlModReq(void);
/* PL2Com Definition for EduPriv_ACU_EmTqTgt */
#define PL2COM_DEF_PL_CVT_EDUPRIV_ACU_EMTQTGT
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduPriv_ACU_EmTqTgt(void);
/* PL2Com Definition for EduPriv_ACU_OperSt */
#define PL2COM_DEF_PL_CVT_EDUPRIV_ACU_OPERST
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduPriv_ACU_OperSt(void);
/* PL2Com Definition for EduPriv_ACU_TqLimMax */
#define PL2COM_DEF_PL_CVT_EDUPRIV_ACU_TQLIMMAX
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduPriv_ACU_TqLimMax(void);
/* PL2Com Definition for EduPriv_ACU_TqLimMin */
#define PL2COM_DEF_PL_CVT_EDUPRIV_ACU_TQLIMMIN
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduPriv_ACU_TqLimMin(void);
/* PL2Com Definition for EduPriv_ACU_TqLimReq */
#define PL2COM_DEF_PL_CVT_EDUPRIV_ACU_TQLIMREQ
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduPriv_ACU_TqLimReq(void);
#include <gmem.h>
#endif
