/****************************************************************************
 * COPYRIGHT VITESCO TECHNOLOGIES GROUP AG (EXCLUSIVE RIGHTS) 
 * Confidential
 * 
 * The reproduction, transmission or use of this document or its
 * contents is not permitted without express written authority.
 * Offenders will be liable for damages. All rights, including rights
 * created by patent grant or registration of a utility model or design,
 * are reserved.
 *---------------------------------------------------------------------------
 * 
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 * !!! This file is generated by Signal Mapper (SIMA) Code-Generator !!!
 * !!! Do NOT modify this file manually                            !!!
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 * 
 * Purpose:    PL Hook Header for data H File
 * 
 * Processor:  independent
 * Tool chain: 
 *    CG-Version:        6.2.0
 *    Schema-Version:    1.18.0
 *    Generation-Date:   03.09.2024  15:13:28  
 *    Generated by user: uiv10169
 * Filename:   $Workfile$
 * Revision:   $Revision: 1.2 $
 * Author:     $Author: Ling Jiaming (uiv10169) (uiv10169) $
 * Date:       $Date: 2024/09/05 08:20:30CEST $
 * Changes:    $Log: ipl_hook_rx_sec_data.h  $
 * Changes:    Revision 1.2 2024/09/05 08:20:30CEST Ling Jiaming (uiv10169) (uiv10169) 
 * Changes:    add new interface Pl_VehSysDwnTiMins
 * 
****************************************************************************/
#ifndef IPL_HOOK_RX_SEC_DATA_H
#define IPL_HOOK_RX_SEC_DATA_H



/* System-Variable declaration for Pl_AntiJerkEnaSpdThd_Sec */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
extern ICS_PL_FLOAT Pl_AntiJerkEnaSpdThd_Sec;
/* System-Variable declaration for Pl_AntiJerkEna_Sec */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_8
#include <gmem.h>
extern ICS_PL_FLAG Pl_AntiJerkEna_Sec;
/* System-Variable declaration for Pl_AntiJerkGain_Sec */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
extern ICS_PL_FLOAT Pl_AntiJerkGain_Sec;
/* System-Variable declaration for Pl_AntiJerkTqLimMax_Sec */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
extern ICS_PL_FLOAT Pl_AntiJerkTqLimMax_Sec;
/* System-Variable declaration for Pl_AntiJerkTqLimMin_Sec */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
extern ICS_PL_FLOAT Pl_AntiJerkTqLimMin_Sec;
/* System-Variable declaration for Pl_LvUHvsReqExtEna_Sec */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_8
#include <gmem.h>
extern ICS_PL_FLAG Pl_LvUHvsReqExtEna_Sec;
/* System-Variable declaration for Pl_VehCluAxleSet_Sec */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_8
#include <gmem.h>
extern ICS_PL_U8 Pl_VehCluAxleSet_Sec;
/* System-Variable declaration for Pl_VehCooltInvInT_North_Sec */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_8
#include <gmem.h>
extern ICS_PL_FLOAT Pl_VehCooltInvInT_North_Sec;
/* System-Variable declaration for Pl_VehCooltInvInT_South_Sec */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_16
#include <gmem.h>
extern ICS_PL_FLOAT Pl_VehCooltInvInT_South_Sec;
/* System-Variable declaration for Pl_VehCooltInvInVolFlowVld_Sec */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_8
#include <gmem.h>
extern ICS_PL_FLAG Pl_VehCooltInvInVolFlowVld_Sec;
/* System-Variable declaration for Pl_VehCooltInvInVolFlow_Sec */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
extern ICS_PL_FLOAT Pl_VehCooltInvInVolFlow_Sec;
/* System-Variable declaration for Pl_VehHvDcILimMax_Sec */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_16
#include <gmem.h>
extern ICS_PL_U16 Pl_VehHvDcILimMax_Sec;
/* System-Variable declaration for Pl_VehHvDcILimMin_Sec */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_16
#include <gmem.h>
extern ICS_PL_U16 Pl_VehHvDcILimMin_Sec;
/* System-Variable declaration for Pl_VehNetMngtReq_Sec */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_8
#include <gmem.h>
extern ICS_PL_FLAG Pl_VehNetMngtReq_Sec;
/* System-Variable declaration for Pl_VehPeModeReq_Sec */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_8
#include <gmem.h>
extern ICS_PL_U8 Pl_VehPeModeReq_Sec;
/* System-Variable declaration for Pl_VehSysDwnTiMins_Sec */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_16
#include <gmem.h>
extern ICS_PL_U16 Pl_VehSysDwnTiMins_Sec;
/* System-Variable declaration for Pl_VehWhlSpd1_Sec */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
extern ICS_PL_FLOAT Pl_VehWhlSpd1_Sec;
/* System-Variable declaration for Pl_VehWhlSpd2_Sec */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
extern ICS_PL_FLOAT Pl_VehWhlSpd2_Sec;
/* System-Variable declaration for Pl_VehWhlSpdTgt_Sec */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_16
#include <gmem.h>
extern ICS_PL_S16 Pl_VehWhlSpdTgt_Sec;
/* System-Variable declaration for Pl_VehWhlSpdVld1_Sec */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_8
#include <gmem.h>
extern ICS_PL_FLAG Pl_VehWhlSpdVld1_Sec;
/* System-Variable declaration for Pl_VehWhlSpdVld2_Sec */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_8
#include <gmem.h>
extern ICS_PL_FLAG Pl_VehWhlSpdVld2_Sec;
/* System-Variable declaration for Pl_VehWhlTqMaxLim_Sec */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
extern ICS_PL_FLOAT Pl_VehWhlTqMaxLim_Sec;
/* System-Variable declaration for Pl_VehWhlTqMinLim_Sec */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
extern ICS_PL_FLOAT Pl_VehWhlTqMinLim_Sec;
/* System-Variable declaration for Pl_VehWhlTqTgt_Sec */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
extern ICS_PL_FLOAT Pl_VehWhlTqTgt_Sec;


#include <gmem.h>
#endif
