/****************************************************************************
 * COPYRIGHT VITESCO TECHNOLOGIES GROUP AG (EXCLUSIVE RIGHTS) 
 * Confidential
 * 
 * The reproduction, transmission or use of this document or its
 * contents is not permitted without express written authority.
 * Offenders will be liable for damages. All rights, including rights
 * created by patent grant or registration of a utility model or design,
 * are reserved.
 *---------------------------------------------------------------------------
 * 
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 * !!! This file is generated by Signal Mapper (SIMA) Code-Generator !!!
 * !!! Do NOT modify this file manually                            !!!
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 * 
 * Purpose:    PL Hook Header
 * 
 * Processor:  independent
 * Tool chain: 
 *    CG-Version:        6.2.0
 *    Schema-Version:    1.18.0
 *    Generation-Date:   29.08.2024  16:59:16  
 *    Generated by user: uiv00534
 * Filename:   $Workfile$
 * Revision:   $Revision: 1.1 $
 * Author:     $Author: Zhang Yi (uiv00534) (uiv00534) $
 * Date:       $Date: 2024/09/03 03:20:49CEST $
 * Changes:    $Log: ipl_hook_tx_prim.h  $
 * Changes:    Revision 1.1 2024/09/03 03:20:49CEST Zhang Yi (uiv00534) (uiv00534) 
 * Changes:    Initial revision
 * Changes:    Member added to project /ES/FS/0G/H0D/0A/bsw/intc/intc_sigcv_mc1/i/project.pj
 * 
****************************************************************************/
#ifndef IPL_HOOK_TX_PRIM_H
#define IPL_HOOK_TX_PRIM_H

#include <ipl_pcnf.h>


/* Variant-IDs */
#ifndef BSample
  #define BSample 1U
#endif


#define  MEM_CODE            ICS_PL_MEM_CODE_SERVICE
#include <gmem.h>


/* PL2Com Definition for EDU1_activeDischFeatEn */
#define PL2COM_DEF_PL_CVT_EDU1_ACTIVEDISCHFEATEN
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EDU1_activeDischFeatEn(void);
/* PL2Com Definition for EDU1_clutchState */
#define PL2COM_DEF_PL_CVT_EDU1_CLUTCHSTATE
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EDU1_clutchState(void);
/* PL2Com Definition for EDU1_comStatusPrimary */
#define PL2COM_DEF_PL_CVT_EDU1_COMSTATUSPRIMARY
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EDU1_comStatusPrimary(void);
/* PL2Com Definition for EDU1_comStatusSecondary */
#define PL2COM_DEF_PL_CVT_EDU1_COMSTATUSSECONDARY
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EDU1_comStatusSecondary(void);
/* PL2Com Definition for EDU1_currentDc */
#define PL2COM_DEF_PL_CVT_EDU1_CURRENTDC
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EDU1_currentDc(void);
/* PL2Com Definition for EDU1_igbtTemp */
#define PL2COM_DEF_PL_CVT_EDU1_IGBTTEMP
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EDU1_igbtTemp(void);
/* PL2Com Definition for EDU1_inverterAppBuildType */
#define PL2COM_DEF_PL_CVT_EDU1_INVERTERAPPBUILDTYPE
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EDU1_inverterAppBuildType(void);
/* PL2Com Definition for EDU1_inverterAppChecksum */
#define PL2COM_DEF_PL_CVT_EDU1_INVERTERAPPCHECKSUM
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EDU1_inverterAppChecksum(void);
/* PL2Com Definition for EDU1_inverterAppInfoMultiplexer_0 */
#define PL2COM_DEF_PL_CVT_EDU1_INVERTERAPPINFOMULTIPLEXER_0
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EDU1_inverterAppInfoMultiplexer_0(void);
/* PL2Com Definition for EDU1_inverterAppInfoMultiplexer_1 */
#define PL2COM_DEF_PL_CVT_EDU1_INVERTERAPPINFOMULTIPLEXER_1
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EDU1_inverterAppInfoMultiplexer_1(void);
/* PL2Com Definition for EDU1_inverterAppInfoMultiplexer_2 */
#define PL2COM_DEF_PL_CVT_EDU1_INVERTERAPPINFOMULTIPLEXER_2
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EDU1_inverterAppInfoMultiplexer_2(void);
/* PL2Com Definition for EDU1_inverterAppVersionMajor */
#define PL2COM_DEF_PL_CVT_EDU1_INVERTERAPPVERSIONMAJOR
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EDU1_inverterAppVersionMajor(void);
/* PL2Com Definition for EDU1_inverterAppVersionMinor */
#define PL2COM_DEF_PL_CVT_EDU1_INVERTERAPPVERSIONMINOR
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EDU1_inverterAppVersionMinor(void);
/* PL2Com Definition for EDU1_inverterAppVersionRev */
#define PL2COM_DEF_PL_CVT_EDU1_INVERTERAPPVERSIONREV
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EDU1_inverterAppVersionRev(void);
/* PL2Com Definition for EDU1_inverterBootInfoVersionRev */
#define PL2COM_DEF_PL_CVT_EDU1_INVERTERBOOTINFOVERSIONREV
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EDU1_inverterBootInfoVersionRev(void);
/* PL2Com Definition for EDU1_inverterBootInfoVersnMajor */
#define PL2COM_DEF_PL_CVT_EDU1_INVERTERBOOTINFOVERSNMAJOR
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EDU1_inverterBootInfoVersnMajor(void);
/* PL2Com Definition for EDU1_inverterBootInfoVersnMinor */
#define PL2COM_DEF_PL_CVT_EDU1_INVERTERBOOTINFOVERSNMINOR
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EDU1_inverterBootInfoVersnMinor(void);
/* PL2Com Definition for EDU1_inverterComponentId */
#define PL2COM_DEF_PL_CVT_EDU1_INVERTERCOMPONENTID
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EDU1_inverterComponentId(void);
/* PL2Com Definition for EDU1_inverterHardwareId */
#define PL2COM_DEF_PL_CVT_EDU1_INVERTERHARDWAREID
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EDU1_inverterHardwareId(void);
/* PL2Com Definition for EDU1_inverterInstanceId */
#define PL2COM_DEF_PL_CVT_EDU1_INVERTERINSTANCEID
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EDU1_inverterInstanceId(void);
/* PL2Com Definition for EDU1_inverterState */
#define PL2COM_DEF_PL_CVT_EDU1_INVERTERSTATE
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EDU1_inverterState(void);
/* PL2Com Definition for EDU1_nmAbleToSleep */
#define PL2COM_DEF_PL_CVT_EDU1_NMABLETOSLEEP
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EDU1_nmAbleToSleep(void);
/* PL2Com Definition for EDU1_nmSleepError */
#define PL2COM_DEF_PL_CVT_EDU1_NMSLEEPERROR
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EDU1_nmSleepError(void);
/* PL2Com Definition for EDU1_nmState */
#define PL2COM_DEF_PL_CVT_EDU1_NMSTATE
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EDU1_nmState(void);
/* PL2Com Definition for EDU1_outputShaftTorque */
#define PL2COM_DEF_PL_CVT_EDU1_OUTPUTSHAFTTORQUE
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EDU1_outputShaftTorque(void);
/* PL2Com Definition for EDU1_outputShaftTorqueLimMax */
#define PL2COM_DEF_PL_CVT_EDU1_OUTPUTSHAFTTORQUELIMMAX
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EDU1_outputShaftTorqueLimMax(void);
/* PL2Com Definition for EDU1_outputShaftTorqueLimMin */
#define PL2COM_DEF_PL_CVT_EDU1_OUTPUTSHAFTTORQUELIMMIN
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EDU1_outputShaftTorqueLimMin(void);
/* PL2Com Definition for EDU1_outputShaftTorqueValid */
#define PL2COM_DEF_PL_CVT_EDU1_OUTPUTSHAFTTORQUEVALID
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EDU1_outputShaftTorqueValid(void);
/* PL2Com Definition for EDU1_rotorPosition */
#define PL2COM_DEF_PL_CVT_EDU1_ROTORPOSITION
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EDU1_rotorPosition(void);
/* PL2Com Definition for EDU1_rotorPositionValid */
#define PL2COM_DEF_PL_CVT_EDU1_ROTORPOSITIONVALID
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EDU1_rotorPositionValid(void);
/* PL2Com Definition for EDU1_rotorSpeed */
#define PL2COM_DEF_PL_CVT_EDU1_ROTORSPEED
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EDU1_rotorSpeed(void);
/* PL2Com Definition for EDU1_rotorSpeedValid */
#define PL2COM_DEF_PL_CVT_EDU1_ROTORSPEEDVALID
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EDU1_rotorSpeedValid(void);
/* PL2Com Definition for EDU1_rotorTemp */
#define PL2COM_DEF_PL_CVT_EDU1_ROTORTEMP
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EDU1_rotorTemp(void);
/* PL2Com Definition for EDU1_statorTemp */
#define PL2COM_DEF_PL_CVT_EDU1_STATORTEMP
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EDU1_statorTemp(void);
/* PL2Com Definition for EduPrim_EDU1_heatPower */
#define PL2COM_DEF_PL_CVT_EDUPRIM_EDU1_HEATPOWER
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduPrim_EDU1_heatPower(void);
/* PL2Com Definition for EduPrim_EDU1_heatPowerLimit */
#define PL2COM_DEF_PL_CVT_EDUPRIM_EDU1_HEATPOWERLIMIT
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduPrim_EDU1_heatPowerLimit(void);
/* PL2Com Definition for EduPrim_EDU_a000_to_a031 */
#define PL2COM_DEF_PL_CVT_EDUPRIM_EDU_A000_TO_A031
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduPrim_EDU_a000_to_a031(void);
/* PL2Com Definition for EduPrim_EDU_a032_to_a059 */
#define PL2COM_DEF_PL_CVT_EDUPRIM_EDU_A032_TO_A059
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduPrim_EDU_a032_to_a059(void);
/* PL2Com Definition for EduPrim_EDU_alertStatusMult_0 */
#define PL2COM_DEF_PL_CVT_EDUPRIM_EDU_ALERTSTATUSMULT_0
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduPrim_EDU_alertStatusMult_0(void);
/* PL2Com Definition for EduPrim_EDU_voltageDc */
#define PL2COM_DEF_PL_CVT_EDUPRIM_EDU_VOLTAGEDC
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduPrim_EDU_voltageDc(void);
#include <gmem.h>
#endif
