/****************************************************************************
 * COPYRIGHT VITESCO TECHNOLOGIES GROUP AG (EXCLUSIVE RIGHTS) 
 * Confidential
 * 
 * The reproduction, transmission or use of this document or its
 * contents is not permitted without express written authority.
 * Offenders will be liable for damages. All rights, including rights
 * created by patent grant or registration of a utility model or design,
 * are reserved.
 *---------------------------------------------------------------------------
 * 
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 * !!! This file is generated by Signal Mapper (SIMA) Code-Generator !!!
 * !!! Do NOT modify this file manually                            !!!
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 * 
 * Purpose:    PL Hook Header
 * 
 * Processor:  independent
 * Tool chain: 
 *    CG-Version:        6.2.0
 *    Schema-Version:    1.18.0
 *    Generation-Date:   03.09.2024  15:13:28  
 *    Generated by user: uiv10169
 * Filename:   $Workfile$
 * Revision:   $Revision: 1.2 $
 * Author:     $Author: Ling Jiaming (uiv10169) (uiv10169) $
 * Date:       $Date: 2024/09/05 08:20:28CEST $
 * Changes:    $Log: ipl_hook_rx_prim.h  $
 * Changes:    Revision 1.2 2024/09/05 08:20:28CEST Ling Jiaming (uiv10169) (uiv10169) 
 * Changes:    add new interface Pl_VehSysDwnTiMins
 * 
****************************************************************************/
#ifndef IPL_HOOK_RX_PRIM_H
#define IPL_HOOK_RX_PRIM_H

#include <ipl_pcnf.h>
#include "pl2com_handleid.h"


/* Variant-IDs */
#ifndef BSample
  #define BSample 1U
#endif


#define  MEM_CODE            ICS_PL_MEM_CODE_SERVICE
#include <gmem.h>



/* PL2Com Definition for EduPrim_EMU_EDU_antiJerkEnable */
#define PL2COM_DEF_PL_CVT_EDUPRIM_EMU_EDU_ANTIJERKENABLE
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduPrim_EMU_EDU_antiJerkEnable(void);
/* PL2Com Definition for EduPrim_EMU_EDU_antiJerkGain */
#define PL2COM_DEF_PL_CVT_EDUPRIM_EMU_EDU_ANTIJERKGAIN
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduPrim_EMU_EDU_antiJerkGain(void);
/* PL2Com Definition for EduPrim_EMU_EDU_antiJerkMaxTorq */
#define PL2COM_DEF_PL_CVT_EDUPRIM_EMU_EDU_ANTIJERKMAXTORQ
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduPrim_EMU_EDU_antiJerkMaxTorq(void);
/* PL2Com Definition for EduPrim_EMU_EDU_antiJerkMinTorq */
#define PL2COM_DEF_PL_CVT_EDUPRIM_EMU_EDU_ANTIJERKMINTORQ
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduPrim_EMU_EDU_antiJerkMinTorq(void);
/* PL2Com Definition for EduPrim_EMU_EDU_antiJerkSpeedThres */
#define PL2COM_DEF_PL_CVT_EDUPRIM_EMU_EDU_ANTIJERKSPEEDTHRES
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduPrim_EMU_EDU_antiJerkSpeedThres(void);
/* PL2Com Definition for EduPrim_EMU_EDU_clutchReq */
#define PL2COM_DEF_PL_CVT_EDUPRIM_EMU_EDU_CLUTCHREQ
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduPrim_EMU_EDU_clutchReq(void);
/* PL2Com Definition for EduPrim_EMU_EDU_hvOnRequest */
#define PL2COM_DEF_PL_CVT_EDUPRIM_EMU_EDU_HVONREQUEST
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduPrim_EMU_EDU_hvOnRequest(void);
/* PL2Com Definition for EduPrim_EMU_EDU_iLimitMax */
#define PL2COM_DEF_PL_CVT_EDUPRIM_EMU_EDU_ILIMITMAX
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduPrim_EMU_EDU_iLimitMax(void);
/* PL2Com Definition for EduPrim_EMU_EDU_iLimitMin */
#define PL2COM_DEF_PL_CVT_EDUPRIM_EMU_EDU_ILIMITMIN
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduPrim_EMU_EDU_iLimitMin(void);
/* PL2Com Definition for EduPrim_EMU_EDU_inverterStateReq */
#define PL2COM_DEF_PL_CVT_EDUPRIM_EMU_EDU_INVERTERSTATEREQ
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduPrim_EMU_EDU_inverterStateReq(void);
/* PL2Com Definition for EduPrim_EMU_EDU_outputShaftTorqueReq */
#define PL2COM_DEF_PL_CVT_EDUPRIM_EMU_EDU_OUTPUTSHAFTTORQUEREQ
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduPrim_EMU_EDU_outputShaftTorqueReq(void);
/* PL2Com Definition for EduPrim_EMU_EDU_outputShaftTrqMax */
#define PL2COM_DEF_PL_CVT_EDUPRIM_EMU_EDU_OUTPUTSHAFTTRQMAX
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduPrim_EMU_EDU_outputShaftTrqMax(void);
/* PL2Com Definition for EduPrim_EMU_EDU_outputShaftTrqMin */
#define PL2COM_DEF_PL_CVT_EDUPRIM_EMU_EDU_OUTPUTSHAFTTRQMIN
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduPrim_EMU_EDU_outputShaftTrqMin(void);
/* PL2Com Definition for EduPrim_EMU_EDU_pwtCoolantFlow */
#define PL2COM_DEF_PL_CVT_EDUPRIM_EMU_EDU_PWTCOOLANTFLOW
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduPrim_EMU_EDU_pwtCoolantFlow(void);
/* PL2Com Definition for EduPrim_EMU_EDU_pwtCoolantFlowValid */
#define PL2COM_DEF_PL_CVT_EDUPRIM_EMU_EDU_PWTCOOLANTFLOWVALID
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduPrim_EMU_EDU_pwtCoolantFlowValid(void);
/* PL2Com Definition for EduPrim_EMU_EDU_systemDowntime */
#define PL2COM_DEF_PL_CVT_EDUPRIM_EMU_EDU_SYSTEMDOWNTIME
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduPrim_EMU_EDU_systemDowntime(void);
/* PL2Com Definition for EduPrim_EMU_EDU_wheelRpmGbxSide */
#define PL2COM_DEF_PL_CVT_EDUPRIM_EMU_EDU_WHEELRPMGBXSIDE
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduPrim_EMU_EDU_wheelRpmGbxSide(void);
/* PL2Com Definition for EduPrim_EMU_EDU_wheelRpmMtrSide */
#define PL2COM_DEF_PL_CVT_EDUPRIM_EMU_EDU_WHEELRPMMTRSIDE
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduPrim_EMU_EDU_wheelRpmMtrSide(void);
/* PL2Com Definition for EduPrim_EMU_EDU_wheelRpmValidGbxSide */
#define PL2COM_DEF_PL_CVT_EDUPRIM_EMU_EDU_WHEELRPMVALIDGBXSIDE
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduPrim_EMU_EDU_wheelRpmValidGbxSide(void);
/* PL2Com Definition for EduPrim_EMU_EDU_wheelRpmValidMtrSide */
#define PL2COM_DEF_PL_CVT_EDUPRIM_EMU_EDU_WHEELRPMVALIDMTRSIDE
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduPrim_EMU_EDU_wheelRpmValidMtrSide(void);
/* PL2Com Definition for EduPrim_EMU_EDU_wheelSpeedTarget */
#define PL2COM_DEF_PL_CVT_EDUPRIM_EMU_EDU_WHEELSPEEDTARGET
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduPrim_EMU_EDU_wheelSpeedTarget(void);
/* PL2Com Definition for EduPrim_EMU_nmStateReq */
#define PL2COM_DEF_PL_CVT_EDUPRIM_EMU_NMSTATEREQ
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduPrim_EMU_nmStateReq(void);
/* PL2Com Definition for EduPrim_TBC_EMU_inverterInletNorthTemp */
#define PL2COM_DEF_PL_CVT_EDUPRIM_TBC_EMU_INVERTERINLETNORTHTEMP
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduPrim_TBC_EMU_inverterInletNorthTemp(void);
/* PL2Com Definition for EduPrim_TBC_EMU_inverterInletSouthTemp */
#define PL2COM_DEF_PL_CVT_EDUPRIM_TBC_EMU_INVERTERINLETSOUTHTEMP
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduPrim_TBC_EMU_inverterInletSouthTemp(void);
#include <gmem.h>
#endif
