/****************************************************************************
 * COPYRIGHT VITESCO TECHNOLOGIES GROUP AG (EXCLUSIVE RIGHTS) 
 * Confidential
 * 
 * The reproduction, transmission or use of this document or its
 * contents is not permitted without express written authority.
 * Offenders will be liable for damages. All rights, including rights
 * created by patent grant or registration of a utility model or design,
 * are reserved.
 *---------------------------------------------------------------------------
 * 
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 * !!! This file is generated by Signal Mapper (SIMA) Code-Generator !!!
 * !!! Do NOT modify this file manually                            !!!
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 * 
 * Purpose:    PL Hook Header for data H File
 * 
 * Processor:  independent
 * Tool chain: 
 *    CG-Version:        6.2.0
 *    Schema-Version:    1.18.0
 *    Generation-Date:   03.09.2024  15:13:28  
 *    Generated by user: uiv10169
 * Filename:   $Workfile$
 * Revision:   $Revision: 1.2 $
 * Author:     $Author: Ling Jiaming (uiv10169) (uiv10169) $
 * Date:       $Date: 2024/09/05 08:20:30CEST $
 * Changes:    $Log: ipl_hook_rx_prim_data.h  $
 * Changes:    Revision 1.2 2024/09/05 08:20:30CEST Ling Jiaming (uiv10169) (uiv10169) 
 * Changes:    add new interface Pl_VehSysDwnTiMins
 * 
****************************************************************************/
#ifndef IPL_HOOK_RX_PRIM_DATA_H
#define IPL_HOOK_RX_PRIM_DATA_H



/* System-Variable declaration for Pl_AntiJerkEna */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_8
#include <gmem.h>
extern ICS_PL_FLAG Pl_AntiJerkEna;
/* System-Variable declaration for Pl_AntiJerkEnaSpdThd */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
extern ICS_PL_FLOAT Pl_AntiJerkEnaSpdThd;
/* System-Variable declaration for Pl_AntiJerkEnaSpdThd_Prim */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
extern ICS_PL_FLOAT Pl_AntiJerkEnaSpdThd_Prim;
/* System-Variable declaration for Pl_AntiJerkEna_Prim */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_8
#include <gmem.h>
extern ICS_PL_FLAG Pl_AntiJerkEna_Prim;
/* System-Variable declaration for Pl_AntiJerkGain */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
extern ICS_PL_FLOAT Pl_AntiJerkGain;
/* System-Variable declaration for Pl_AntiJerkGain_Prim */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
extern ICS_PL_FLOAT Pl_AntiJerkGain_Prim;
/* System-Variable declaration for Pl_AntiJerkTqLimMax */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
extern ICS_PL_FLOAT Pl_AntiJerkTqLimMax;
/* System-Variable declaration for Pl_AntiJerkTqLimMax_Prim */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
extern ICS_PL_FLOAT Pl_AntiJerkTqLimMax_Prim;
/* System-Variable declaration for Pl_AntiJerkTqLimMin */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
extern ICS_PL_FLOAT Pl_AntiJerkTqLimMin;
/* System-Variable declaration for Pl_AntiJerkTqLimMin_Prim */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
extern ICS_PL_FLOAT Pl_AntiJerkTqLimMin_Prim;
/* System-Variable declaration for Pl_LvUHvsReqExtEna */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_8
#include <gmem.h>
extern ICS_PL_FLAG Pl_LvUHvsReqExtEna;
/* System-Variable declaration for Pl_LvUHvsReqExtEna_Prim */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_8
#include <gmem.h>
extern ICS_PL_FLAG Pl_LvUHvsReqExtEna_Prim;
/* System-Variable declaration for Pl_VehCluAxleSet */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_8
#include <gmem.h>
extern ICS_PL_U8 Pl_VehCluAxleSet;
/* System-Variable declaration for Pl_VehCluAxleSet_Prim */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_8
#include <gmem.h>
extern ICS_PL_U8 Pl_VehCluAxleSet_Prim;
/* System-Variable declaration for Pl_VehCooltInvInT_North */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_16
#include <gmem.h>
extern ICS_PL_FLOAT Pl_VehCooltInvInT_North;
/* System-Variable declaration for Pl_VehCooltInvInT_North_Prim */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_16
#include <gmem.h>
extern ICS_PL_FLOAT Pl_VehCooltInvInT_North_Prim;
/* System-Variable declaration for Pl_VehCooltInvInT_South */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_16
#include <gmem.h>
extern ICS_PL_FLOAT Pl_VehCooltInvInT_South;
/* System-Variable declaration for Pl_VehCooltInvInT_South_Prim */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_16
#include <gmem.h>
extern ICS_PL_FLOAT Pl_VehCooltInvInT_South_Prim;
/* System-Variable declaration for Pl_VehCooltInvInVolFlow */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
extern ICS_PL_FLOAT Pl_VehCooltInvInVolFlow;
/* System-Variable declaration for Pl_VehCooltInvInVolFlowVld */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_8
#include <gmem.h>
extern ICS_PL_FLAG Pl_VehCooltInvInVolFlowVld;
/* System-Variable declaration for Pl_VehCooltInvInVolFlowVld_Prim */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_8
#include <gmem.h>
extern ICS_PL_FLAG Pl_VehCooltInvInVolFlowVld_Prim;
/* System-Variable declaration for Pl_VehCooltInvInVolFlow_Prim */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
extern ICS_PL_FLOAT Pl_VehCooltInvInVolFlow_Prim;
/* System-Variable declaration for Pl_VehHvDcILimMax */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_16
#include <gmem.h>
extern ICS_PL_U16 Pl_VehHvDcILimMax;
/* System-Variable declaration for Pl_VehHvDcILimMax_Prim */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_16
#include <gmem.h>
extern ICS_PL_U16 Pl_VehHvDcILimMax_Prim;
/* System-Variable declaration for Pl_VehHvDcILimMin */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_16
#include <gmem.h>
extern ICS_PL_U16 Pl_VehHvDcILimMin;
/* System-Variable declaration for Pl_VehHvDcILimMin_Prim */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_16
#include <gmem.h>
extern ICS_PL_U16 Pl_VehHvDcILimMin_Prim;
/* System-Variable declaration for Pl_VehNetMngtReq */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_8
#include <gmem.h>
extern ICS_PL_FLAG Pl_VehNetMngtReq;
/* System-Variable declaration for Pl_VehNetMngtReq_Prim */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_8
#include <gmem.h>
extern ICS_PL_FLAG Pl_VehNetMngtReq_Prim;
/* System-Variable declaration for Pl_VehPeModeReq */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_8
#include <gmem.h>
extern ICS_PL_U8 Pl_VehPeModeReq;
/* System-Variable declaration for Pl_VehPeModeReq_Prim */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_8
#include <gmem.h>
extern ICS_PL_U8 Pl_VehPeModeReq_Prim;
/* System-Variable declaration for Pl_VehSysDwnTiMins */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_16
#include <gmem.h>
extern ICS_PL_U16 Pl_VehSysDwnTiMins;
/* System-Variable declaration for Pl_VehSysDwnTiMins_Prim */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_16
#include <gmem.h>
extern ICS_PL_U16 Pl_VehSysDwnTiMins_Prim;
/* System-Variable declaration for Pl_VehWhlSpd1 */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
extern ICS_PL_FLOAT Pl_VehWhlSpd1;
/* System-Variable declaration for Pl_VehWhlSpd1_Prim */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
extern ICS_PL_FLOAT Pl_VehWhlSpd1_Prim;
/* System-Variable declaration for Pl_VehWhlSpd2 */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
extern ICS_PL_FLOAT Pl_VehWhlSpd2;
/* System-Variable declaration for Pl_VehWhlSpd2_Prim */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
extern ICS_PL_FLOAT Pl_VehWhlSpd2_Prim;
/* System-Variable declaration for Pl_VehWhlSpdTgt */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_16
#include <gmem.h>
extern ICS_PL_S16 Pl_VehWhlSpdTgt;
/* System-Variable declaration for Pl_VehWhlSpdTgt_Prim */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_16
#include <gmem.h>
extern ICS_PL_S16 Pl_VehWhlSpdTgt_Prim;
/* System-Variable declaration for Pl_VehWhlSpdVld1 */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_8
#include <gmem.h>
extern ICS_PL_FLAG Pl_VehWhlSpdVld1;
/* System-Variable declaration for Pl_VehWhlSpdVld1_Prim */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_8
#include <gmem.h>
extern ICS_PL_FLAG Pl_VehWhlSpdVld1_Prim;
/* System-Variable declaration for Pl_VehWhlSpdVld2 */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_8
#include <gmem.h>
extern ICS_PL_FLAG Pl_VehWhlSpdVld2;
/* System-Variable declaration for Pl_VehWhlSpdVld2_Prim */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_8
#include <gmem.h>
extern ICS_PL_FLAG Pl_VehWhlSpdVld2_Prim;
/* System-Variable declaration for Pl_VehWhlTqMaxLim */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
extern ICS_PL_FLOAT Pl_VehWhlTqMaxLim;
/* System-Variable declaration for Pl_VehWhlTqMaxLim_Prim */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
extern ICS_PL_FLOAT Pl_VehWhlTqMaxLim_Prim;
/* System-Variable declaration for Pl_VehWhlTqMinLim */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
extern ICS_PL_FLOAT Pl_VehWhlTqMinLim;
/* System-Variable declaration for Pl_VehWhlTqMinLim_Prim */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
extern ICS_PL_FLOAT Pl_VehWhlTqMinLim_Prim;
/* System-Variable declaration for Pl_VehWhlTqTgt */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
extern ICS_PL_FLOAT Pl_VehWhlTqTgt;
/* System-Variable declaration for Pl_VehWhlTqTgt_Prim */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
extern ICS_PL_FLOAT Pl_VehWhlTqTgt_Prim;


#include <gmem.h>
#endif
