/****************************************************************************
 * COPYRIGHT VITESCO TECHNOLOGIES GROUP AG (EXCLUSIVE RIGHTS) 
 * Confidential
 * 
 * The reproduction, transmission or use of this document or its
 * contents is not permitted without express written authority.
 * Offenders will be liable for damages. All rights, including rights
 * created by patent grant or registration of a utility model or design,
 * are reserved.
 *---------------------------------------------------------------------------
 * 
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 * !!! This file is generated by Signal Mapper (SIMA) Code-Generator !!!
 * !!! Do NOT modify this file manually                            !!!
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 * 
 * Purpose:    PL Hook Header for MCR
 * 
 * Processor:  independent
 * Tool chain: 
 *    CG-Version:        6.2.0
 *    Schema-Version:    1.18.0
 *    Generation-Date:   29.08.2024  16:59:16  
 *    Generated by user: uiv00534
 * Filename:   $Workfile$
 * Revision:   $Revision: 1.1 $
 * Author:     $Author: Zhang Yi (uiv00534) (uiv00534) $
 * Date:       $Date: 2024/09/03 03:20:51CEST $
 * Changes:    $Log: ipl_hook_tx_sec_mcr.h  $
 * Changes:    Revision 1.1 2024/09/03 03:20:51CEST Zhang Yi (uiv00534) (uiv00534) 
 * Changes:    Initial revision
 * Changes:    Member added to project /ES/FS/0G/H0D/0A/bsw/intc/intc_sigcv_mc1/i/project.pj
 * 
****************************************************************************/
#ifndef IPL_HOOK_TX_SEC_MCR_H
#define IPL_HOOK_TX_SEC_MCR_H

#undef ACTION_ID_NONE
#undef RUNNABLE_ID_NONE
#define ACTION_ID_NONE 0
#define RUNNABLE_ID_NONE 0

#define ACTION_ID_PL_Cvt_EduSec_EDU_activeDischFeatEn 68
#define ACTION_ID_PL_Cvt_EduSec_EDU_clutchState 69
#define ACTION_ID_PL_Cvt_EduSec_EDU_comStatusPrimary 70
#define ACTION_ID_PL_Cvt_EduSec_EDU_comStatusSecondary 71
#define ACTION_ID_PL_Cvt_EduSec_EDU_currentDc 72
#define ACTION_ID_PL_Cvt_EduSec_EDU_heatPower 73
#define ACTION_ID_PL_Cvt_EduSec_EDU_heatPowerLimit 74
#define ACTION_ID_PL_Cvt_EduSec_EDU_igbtTemp 75
#define ACTION_ID_PL_Cvt_EduSec_EDU_inverterState 76
#define ACTION_ID_PL_Cvt_EduSec_EDU_nmAbleToSleep 77
#define ACTION_ID_PL_Cvt_EduSec_EDU_nmSleepError 78
#define ACTION_ID_PL_Cvt_EduSec_EDU_nmState 79
#define ACTION_ID_PL_Cvt_EduSec_EDU_outputShaftTorque 80
#define ACTION_ID_PL_Cvt_EduSec_EDU_outputShaftTorqueLimMax 81
#define ACTION_ID_PL_Cvt_EduSec_EDU_outputShaftTorqueLimMin 82
#define ACTION_ID_PL_Cvt_EduSec_EDU_outputShaftTorqueValid 83
#define ACTION_ID_PL_Cvt_EduSec_EDU_rotorPosition 84
#define ACTION_ID_PL_Cvt_EduSec_EDU_rotorPositionValid 85
#define ACTION_ID_PL_Cvt_EduSec_EDU_rotorSpeed 86
#define ACTION_ID_PL_Cvt_EduSec_EDU_rotorSpeedValid 87
#define ACTION_ID_PL_Cvt_EduSec_EDU_rotorTemp 88
#define ACTION_ID_PL_Cvt_EduSec_EDU_statorTemp 89
#define ACTION_ID_PL_Cvt_EduSec_EDU_voltageDc 90
#endif

#if !(defined RUNNABLE_ID || defined ACTION_ID)
#error "No RUNNABLE_ID or ACTION_ID defined"
#endif
#ifndef RUNNABLE_ID
#define RUNNABLE_ID RUNNABLE_ID_NONE
#endif
#ifndef ACTION_ID
#define ACTION_ID ACTION_ID_NONE
#endif


/* Getters and setters for everyone */
#ifdef BNmAbleToSleep
  #ifndef GET_bNmAbleToSleep
    #define GET_bNmAbleToSleep() (BNmAbleToSleep())
  #endif
#else
  #ifndef GET_bNmAbleToSleep
    #define GET_bNmAbleToSleep() (bNmAbleToSleep)
  #endif
#endif
#ifdef ECanNmState
  #ifndef GET_eCanNmState
    #define GET_eCanNmState() (ECanNmState())
  #endif
#else
  #ifndef GET_eCanNmState
    #define GET_eCanNmState() (eCanNmState)
  #endif
#endif
#ifdef F32AngRotorEstim
  #ifndef GET_f32AngRotorEstim
    #define GET_f32AngRotorEstim() (1 /*F32AngRotorEstim() */)
  #endif
#else
  #ifndef GET_f32AngRotorEstim
    #define GET_f32AngRotorEstim() (1 /*F32AngRotorEstim() */)
  #endif
#endif
#ifdef F32NRotorLpfSlow
  #ifndef GET_f32NRotorLpfSlow
    #define GET_f32NRotorLpfSlow() (1 /* F32NRotorLpfSlow() */)
  #endif
#else
  #ifndef GET_f32NRotorLpfSlow
    #define GET_f32NRotorLpfSlow() (1 /* F32NRotorLpfSlow() */)
  #endif
#endif
#ifdef Pl_AcvDchaSts
  #ifndef GET_Pl_AcvDchaSts
    #define GET_Pl_AcvDchaSts() (Pl_AcvDchaSts())
  #endif
#else
  #ifndef GET_Pl_AcvDchaSts
    #define GET_Pl_AcvDchaSts() (Pl_AcvDchaSts)
  #endif
#endif
#ifdef Pl_CluAxleSt
  #ifndef GET_Pl_CluAxleSt
    #define GET_Pl_CluAxleSt() (Pl_CluAxleSt())
  #endif
#else
  #ifndef GET_Pl_CluAxleSt
    #define GET_Pl_CluAxleSt() (Pl_CluAxleSt)
  #endif
#endif
#ifdef Pl_EmRotorTEstimd
  #ifndef GET_Pl_EmRotorTEstimd
    #define GET_Pl_EmRotorTEstimd() (Pl_EmRotorTEstimd())
  #endif
#else
  #ifndef GET_Pl_EmRotorTEstimd
    #define GET_Pl_EmRotorTEstimd() (Pl_EmRotorTEstimd)
  #endif
#endif
#ifdef Pl_EmStatorTHotSpotEstimd
  #ifndef GET_Pl_EmStatorTHotSpotEstimd
    #define GET_Pl_EmStatorTHotSpotEstimd() (Pl_EmStatorTHotSpotEstimd())
  #endif
#else
  #ifndef GET_Pl_EmStatorTHotSpotEstimd
    #define GET_Pl_EmStatorTHotSpotEstimd() (Pl_EmStatorTHotSpotEstimd)
  #endif
#endif
#ifdef Pl_HvDcIEstimd
  #ifndef GET_Pl_HvDcIEstimd
    #define GET_Pl_HvDcIEstimd() (Pl_HvDcIEstimd())
  #endif
#else
  #ifndef GET_Pl_HvDcIEstimd
    #define GET_Pl_HvDcIEstimd() (Pl_HvDcIEstimd)
  #endif
#endif
#ifdef Pl_HvDcUMeasd
  #ifndef GET_Pl_HvDcUMeasd
    #define GET_Pl_HvDcUMeasd() (Pl_HvDcUMeasd())
  #endif
#else
  #ifndef GET_Pl_HvDcUMeasd
    #define GET_Pl_HvDcUMeasd() (Pl_HvDcUMeasd)
  #endif
#endif
#ifdef Pl_LvStPosnRotorVld
  #ifndef GET_Pl_LvStPosnRotorVld
    #define GET_Pl_LvStPosnRotorVld() (Pl_LvStPosnRotorVld())
  #endif
#else
  #ifndef GET_Pl_LvStPosnRotorVld
    #define GET_Pl_LvStPosnRotorVld() (Pl_LvStPosnRotorVld)
  #endif
#endif
#ifdef Pl_PeIgbtDiodeT
  #ifndef GET_Pl_PeIgbtDiodeT
    #define GET_Pl_PeIgbtDiodeT() (Pl_PeIgbtDiodeT())
  #endif
#else
  #ifndef GET_Pl_PeIgbtDiodeT
    #define GET_Pl_PeIgbtDiodeT() (Pl_PeIgbtDiodeT)
  #endif
#endif
#ifdef Pl_PeModeAct
  #ifndef GET_Pl_PeModeAct
    #define GET_Pl_PeModeAct() (Pl_PeModeAct())
  #endif
#else
  #ifndef GET_Pl_PeModeAct
    #define GET_Pl_PeModeAct() (Pl_PeModeAct)
  #endif
#endif
#ifdef Pl_PwrLossElInvt
  #ifndef GET_Pl_PwrLossElInvt
    #define GET_Pl_PwrLossElInvt() (Pl_PwrLossElInvt())
  #endif
#else
  #ifndef GET_Pl_PwrLossElInvt
    #define GET_Pl_PwrLossElInvt() (Pl_PwrLossElInvt)
  #endif
#endif
#ifdef Pl_PwrLossInvtMaxEstim
  #ifndef GET_Pl_PwrLossInvtMaxEstim
    #define GET_Pl_PwrLossInvtMaxEstim() (Pl_PwrLossInvtMaxEstim())
  #endif
#else
  #ifndef GET_Pl_PwrLossInvtMaxEstim
    #define GET_Pl_PwrLossInvtMaxEstim() (Pl_PwrLossInvtMaxEstim)
  #endif
#endif
#ifdef Pl_WhlTqEstimdAct
  #ifndef GET_Pl_WhlTqEstimdAct
    #define GET_Pl_WhlTqEstimdAct() (Pl_WhlTqEstimdAct())
  #endif
#else
  #ifndef GET_Pl_WhlTqEstimdAct
    #define GET_Pl_WhlTqEstimdAct() (Pl_WhlTqEstimdAct)
  #endif
#endif
#ifdef Pl_WhlTqMaxEstimdLimAct
  #ifndef GET_Pl_WhlTqMaxEstimdLimAct
    #define GET_Pl_WhlTqMaxEstimdLimAct() (Pl_WhlTqMaxEstimdLimAct())
  #endif
#else
  #ifndef GET_Pl_WhlTqMaxEstimdLimAct
    #define GET_Pl_WhlTqMaxEstimdLimAct() (Pl_WhlTqMaxEstimdLimAct)
  #endif
#endif
#ifdef Pl_WhlTqMinEstimdLimAct
  #ifndef GET_Pl_WhlTqMinEstimdLimAct
    #define GET_Pl_WhlTqMinEstimdLimAct() (Pl_WhlTqMinEstimdLimAct())
  #endif
#else
  #ifndef GET_Pl_WhlTqMinEstimdLimAct
    #define GET_Pl_WhlTqMinEstimdLimAct() (Pl_WhlTqMinEstimdLimAct)
  #endif
#endif
#ifdef U8ComStatusPrimary
  #ifndef GET_u8ComStatusPrimary
    #define GET_u8ComStatusPrimary() (1 /*U8ComStatusPrimary() */)
  #endif
#else
  #ifndef GET_u8ComStatusPrimary
    #define GET_u8ComStatusPrimary() (1 /*U8ComStatusPrimary() */)
  #endif
#endif
#ifdef U8ComStatusSecondary
  #ifndef GET_u8ComStatusSecondary
    #define GET_u8ComStatusSecondary() (1 /* U8ComStatusSecondary() */ )
  #endif
#else
  #ifndef GET_u8ComStatusSecondary
    #define GET_u8ComStatusSecondary() (1 /* U8ComStatusSecondary() */)
  #endif
#endif

#undef RUNNABLE_ID
#define RUNNABLE_ID RUNNABLE_ID_NONE
#undef ACTION_ID
#define ACTION_ID ACTION_ID_NONE

#if !((RUNNABLE_ID == RUNNABLE_ID_NONE) && (ACTION_ID == RUNNABLE_ID_NONE))
#error "Illegal RUNNABLE_ID or ACTION_ID found"
#endif


