/****************************************************************************
 * COPYRIGHT VITESCO TECHNOLOGIES GROUP AG (EXCLUSIVE RIGHTS) 
 * Confidential
 * 
 * The reproduction, transmission or use of this document or its
 * contents is not permitted without express written authority.
 * Offenders will be liable for damages. All rights, including rights
 * created by patent grant or registration of a utility model or design,
 * are reserved.
 *---------------------------------------------------------------------------
 * 
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 * !!! This file is generated by Signal Mapper (SIMA) Code-Generator !!!
 * !!! Do NOT modify this file manually                            !!!
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 * 
 * Purpose:    PL Hook Header for MCR
 * 
 * Processor:  independent
 * Tool chain: 
 *    CG-Version:        6.2.0
 *    Schema-Version:    1.18.0
 *    Generation-Date:   03.09.2024  15:13:28  
 *    Generated by user: uiv10169
 * Filename:   $Workfile$
 * Revision:   $Revision: 1.2 $
 * Author:     $Author: Ling Jiaming (uiv10169) (uiv10169) $
 * Date:       $Date: 2024/09/05 08:20:27CEST $
 * Changes:    $Log: ipl_hook_rx_prim_mcr.h  $
 * Changes:    Revision 1.2 2024/09/05 08:20:27CEST Ling Jiaming (uiv10169) (uiv10169) 
 * Changes:    add new interface Pl_VehSysDwnTiMins
 * 
****************************************************************************/
#ifndef IPL_HOOK_RX_PRIM_MCR_H
#define IPL_HOOK_RX_PRIM_MCR_H

#undef ACTION_ID_NONE
#undef RUNNABLE_ID_NONE
#define ACTION_ID_NONE 0
#define RUNNABLE_ID_NONE 0

#define ACTION_ID_PL_Cvt_BoolDummy 3
#define ACTION_ID_PL_Cvt_BoolDummyText 4
#define ACTION_ID_PL_Cvt_EduPrim_EMU_EDU_antiJerkEnable 45
#define ACTION_ID_PL_Cvt_EduPrim_EMU_EDU_antiJerkGain 46
#define ACTION_ID_PL_Cvt_EduPrim_EMU_EDU_antiJerkMaxTorq 47
#define ACTION_ID_PL_Cvt_EduPrim_EMU_EDU_antiJerkMinTorq 48
#define ACTION_ID_PL_Cvt_EduPrim_EMU_EDU_antiJerkSpeedThres 49
#define ACTION_ID_PL_Cvt_EduPrim_EMU_EDU_clutchReq 50
#define ACTION_ID_PL_Cvt_EduPrim_EMU_EDU_hvOnRequest 51
#define ACTION_ID_PL_Cvt_EduPrim_EMU_EDU_iLimitMax 52
#define ACTION_ID_PL_Cvt_EduPrim_EMU_EDU_iLimitMin 53
#define ACTION_ID_PL_Cvt_EduPrim_EMU_EDU_inverterStateReq 54
#define ACTION_ID_PL_Cvt_EduPrim_EMU_EDU_outputShaftTorqueReq 55
#define ACTION_ID_PL_Cvt_EduPrim_EMU_EDU_outputShaftTrqMax 56
#define ACTION_ID_PL_Cvt_EduPrim_EMU_EDU_outputShaftTrqMin 57
#define ACTION_ID_PL_Cvt_EduPrim_EMU_EDU_pwtCoolantFlow 58
#define ACTION_ID_PL_Cvt_EduPrim_EMU_EDU_pwtCoolantFlowValid 59
#define ACTION_ID_PL_Cvt_EduPrim_EMU_EDU_systemDowntime 60
#define ACTION_ID_PL_Cvt_EduPrim_EMU_EDU_wheelRpmGbxSide 61
#define ACTION_ID_PL_Cvt_EduPrim_EMU_EDU_wheelRpmMtrSide 62
#define ACTION_ID_PL_Cvt_EduPrim_EMU_EDU_wheelRpmValidGbxSide 63
#define ACTION_ID_PL_Cvt_EduPrim_EMU_EDU_wheelRpmValidMtrSide 64
#define ACTION_ID_PL_Cvt_EduPrim_EMU_EDU_wheelSpeedTarget 65
#define ACTION_ID_PL_Cvt_EduPrim_EMU_nmStateReq 66
#define ACTION_ID_PL_Cvt_EduPrim_TBC_EMU_inverterInletNorthTemp 67
#define ACTION_ID_PL_Cvt_EduPrim_TBC_EMU_inverterInletSouthTemp 68
#define ACTION_ID_PL_Cvt_S16Dummy 116
#define ACTION_ID_PL_Cvt_U16Dummy 117
#define ACTION_ID_PL_Cvt_U8Dummy 118
#define ACTION_ID_PL_Cvt_U8DummyText1 119
#define ACTION_ID_PL_Cvt_U8DummyText2 120
#define ACTION_ID_PL_Cvt_U8DummyText3 121
#endif

#if !(defined RUNNABLE_ID || defined ACTION_ID)
#error "No RUNNABLE_ID or ACTION_ID defined"
#endif
#ifndef RUNNABLE_ID
#define RUNNABLE_ID RUNNABLE_ID_NONE
#endif
#ifndef ACTION_ID
#define ACTION_ID ACTION_ID_NONE
#endif


/* Getters and setters for everyone */
#ifndef SET_Pl_AntiJerkEna
  #define SET_Pl_AntiJerkEna(x) (Pl_AntiJerkEna=(x))
#endif
#ifndef SET_Pl_AntiJerkEna_Prim
  #define SET_Pl_AntiJerkEna_Prim(x) (Pl_AntiJerkEna_Prim=(x))
#endif
#ifndef SET_Pl_AntiJerkEnaSpdThd
  #define SET_Pl_AntiJerkEnaSpdThd(x) (Pl_AntiJerkEnaSpdThd=(x))
#endif
#ifndef SET_Pl_AntiJerkEnaSpdThd_Prim
  #define SET_Pl_AntiJerkEnaSpdThd_Prim(x) (Pl_AntiJerkEnaSpdThd_Prim=(x))
#endif
#ifndef SET_Pl_AntiJerkGain
  #define SET_Pl_AntiJerkGain(x) (Pl_AntiJerkGain=(x))
#endif
#ifndef SET_Pl_AntiJerkGain_Prim
  #define SET_Pl_AntiJerkGain_Prim(x) (Pl_AntiJerkGain_Prim=(x))
#endif
#ifndef SET_Pl_AntiJerkTqLimMax
  #define SET_Pl_AntiJerkTqLimMax(x) (Pl_AntiJerkTqLimMax=(x))
#endif
#ifndef SET_Pl_AntiJerkTqLimMax_Prim
  #define SET_Pl_AntiJerkTqLimMax_Prim(x) (Pl_AntiJerkTqLimMax_Prim=(x))
#endif
#ifndef SET_Pl_AntiJerkTqLimMin
  #define SET_Pl_AntiJerkTqLimMin(x) (Pl_AntiJerkTqLimMin=(x))
#endif
#ifndef SET_Pl_AntiJerkTqLimMin_Prim
  #define SET_Pl_AntiJerkTqLimMin_Prim(x) (Pl_AntiJerkTqLimMin_Prim=(x))
#endif
#ifndef SET_Pl_LvUHvsReqExtEna
  #define SET_Pl_LvUHvsReqExtEna(x) (Pl_LvUHvsReqExtEna=(x))
#endif
#ifndef SET_Pl_LvUHvsReqExtEna_Prim
  #define SET_Pl_LvUHvsReqExtEna_Prim(x) (Pl_LvUHvsReqExtEna_Prim=(x))
#endif
#ifndef SET_Pl_VehCluAxleSet
  #define SET_Pl_VehCluAxleSet(x) (Pl_VehCluAxleSet=(x))
#endif
#ifndef SET_Pl_VehCluAxleSet_Prim
  #define SET_Pl_VehCluAxleSet_Prim(x) (Pl_VehCluAxleSet_Prim=(x))
#endif
#ifndef SET_Pl_VehCooltInvInT_North
  #define SET_Pl_VehCooltInvInT_North(x) (Pl_VehCooltInvInT_North=(x))
#endif
#ifndef SET_Pl_VehCooltInvInT_North_Prim
  #define SET_Pl_VehCooltInvInT_North_Prim(x) (Pl_VehCooltInvInT_North_Prim=(x))
#endif
#ifndef SET_Pl_VehCooltInvInT_South
  #define SET_Pl_VehCooltInvInT_South(x) (Pl_VehCooltInvInT_South=(x))
#endif
#ifndef SET_Pl_VehCooltInvInT_South_Prim
  #define SET_Pl_VehCooltInvInT_South_Prim(x) (Pl_VehCooltInvInT_South_Prim=(x))
#endif
#ifndef SET_Pl_VehCooltInvInVolFlow
  #define SET_Pl_VehCooltInvInVolFlow(x) (Pl_VehCooltInvInVolFlow=(x))
#endif
#ifndef SET_Pl_VehCooltInvInVolFlow_Prim
  #define SET_Pl_VehCooltInvInVolFlow_Prim(x) (Pl_VehCooltInvInVolFlow_Prim=(x))
#endif
#ifndef SET_Pl_VehCooltInvInVolFlowVld
  #define SET_Pl_VehCooltInvInVolFlowVld(x) (Pl_VehCooltInvInVolFlowVld=(x))
#endif
#ifndef SET_Pl_VehCooltInvInVolFlowVld_Prim
  #define SET_Pl_VehCooltInvInVolFlowVld_Prim(x) (Pl_VehCooltInvInVolFlowVld_Prim=(x))
#endif
#ifndef SET_Pl_VehHvDcILimMax
  #define SET_Pl_VehHvDcILimMax(x) (Pl_VehHvDcILimMax=(x))
#endif
#ifndef SET_Pl_VehHvDcILimMax_Prim
  #define SET_Pl_VehHvDcILimMax_Prim(x) (Pl_VehHvDcILimMax_Prim=(x))
#endif
#ifndef SET_Pl_VehHvDcILimMin
  #define SET_Pl_VehHvDcILimMin(x) (Pl_VehHvDcILimMin=(x))
#endif
#ifndef SET_Pl_VehHvDcILimMin_Prim
  #define SET_Pl_VehHvDcILimMin_Prim(x) (Pl_VehHvDcILimMin_Prim=(x))
#endif
#ifndef SET_Pl_VehNetMngtReq
  #define SET_Pl_VehNetMngtReq(x) (Pl_VehNetMngtReq=(x))
#endif
#ifndef SET_Pl_VehNetMngtReq_Prim
  #define SET_Pl_VehNetMngtReq_Prim(x) (Pl_VehNetMngtReq_Prim=(x))
#endif
#ifndef SET_Pl_VehPeModeReq
  #define SET_Pl_VehPeModeReq(x) (Pl_VehPeModeReq=(x))
#endif
#ifndef SET_Pl_VehPeModeReq_Prim
  #define SET_Pl_VehPeModeReq_Prim(x) (Pl_VehPeModeReq_Prim=(x))
#endif
#ifndef SET_Pl_VehSysDwnTiMins
  #define SET_Pl_VehSysDwnTiMins(x) (Pl_VehSysDwnTiMins=(x))
#endif
#ifndef SET_Pl_VehSysDwnTiMins_Prim
  #define SET_Pl_VehSysDwnTiMins_Prim(x) (Pl_VehSysDwnTiMins_Prim=(x))
#endif
#ifndef SET_Pl_VehWhlSpd1
  #define SET_Pl_VehWhlSpd1(x) (Pl_VehWhlSpd1=(x))
#endif
#ifndef SET_Pl_VehWhlSpd1_Prim
  #define SET_Pl_VehWhlSpd1_Prim(x) (Pl_VehWhlSpd1_Prim=(x))
#endif
#ifndef SET_Pl_VehWhlSpd2
  #define SET_Pl_VehWhlSpd2(x) (Pl_VehWhlSpd2=(x))
#endif
#ifndef SET_Pl_VehWhlSpd2_Prim
  #define SET_Pl_VehWhlSpd2_Prim(x) (Pl_VehWhlSpd2_Prim=(x))
#endif
#ifndef SET_Pl_VehWhlSpdTgt
  #define SET_Pl_VehWhlSpdTgt(x) (Pl_VehWhlSpdTgt=(x))
#endif
#ifndef SET_Pl_VehWhlSpdTgt_Prim
  #define SET_Pl_VehWhlSpdTgt_Prim(x) (Pl_VehWhlSpdTgt_Prim=(x))
#endif
#ifndef SET_Pl_VehWhlSpdVld1
  #define SET_Pl_VehWhlSpdVld1(x) (Pl_VehWhlSpdVld1=(x))
#endif
#ifndef SET_Pl_VehWhlSpdVld1_Prim
  #define SET_Pl_VehWhlSpdVld1_Prim(x) (Pl_VehWhlSpdVld1_Prim=(x))
#endif
#ifndef SET_Pl_VehWhlSpdVld2
  #define SET_Pl_VehWhlSpdVld2(x) (Pl_VehWhlSpdVld2=(x))
#endif
#ifndef SET_Pl_VehWhlSpdVld2_Prim
  #define SET_Pl_VehWhlSpdVld2_Prim(x) (Pl_VehWhlSpdVld2_Prim=(x))
#endif
#ifndef SET_Pl_VehWhlTqMaxLim
  #define SET_Pl_VehWhlTqMaxLim(x) (Pl_VehWhlTqMaxLim=(x))
#endif
#ifndef SET_Pl_VehWhlTqMaxLim_Prim
  #define SET_Pl_VehWhlTqMaxLim_Prim(x) (Pl_VehWhlTqMaxLim_Prim=(x))
#endif
#ifndef SET_Pl_VehWhlTqMinLim
  #define SET_Pl_VehWhlTqMinLim(x) (Pl_VehWhlTqMinLim=(x))
#endif
#ifndef SET_Pl_VehWhlTqMinLim_Prim
  #define SET_Pl_VehWhlTqMinLim_Prim(x) (Pl_VehWhlTqMinLim_Prim=(x))
#endif
#ifndef SET_Pl_VehWhlTqTgt
  #define SET_Pl_VehWhlTqTgt(x) (Pl_VehWhlTqTgt=(x))
#endif
#ifndef SET_Pl_VehWhlTqTgt_Prim
  #define SET_Pl_VehWhlTqTgt_Prim(x) (Pl_VehWhlTqTgt_Prim=(x))
#endif

#undef RUNNABLE_ID
#define RUNNABLE_ID RUNNABLE_ID_NONE
#undef ACTION_ID
#define ACTION_ID ACTION_ID_NONE

#if !((RUNNABLE_ID == RUNNABLE_ID_NONE) && (ACTION_ID == RUNNABLE_ID_NONE))
#error "Illegal RUNNABLE_ID or ACTION_ID found"
#endif


