/****************************************************************************
 * COPYRIGHT VITESCO TECHNOLOGIES GROUP AG (EXCLUSIVE RIGHTS) 
 * Confidential
 * 
 * The reproduction, transmission or use of this document or its
 * contents is not permitted without express written authority.
 * Offenders will be liable for damages. All rights, including rights
 * created by patent grant or registration of a utility model or design,
 * are reserved.
 *---------------------------------------------------------------------------
 * 
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 * !!! This file is generated by Signal Mapper (SIMA) Code-Generator !!!
 * !!! Do NOT modify this file manually                            !!!
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 * 
 * Purpose:    PL Hook Header for data C Files
 * 
 * Processor:  independent
 * Tool chain: 
 *    CG-Version:        6.2.0
 *    Schema-Version:    1.18.0
 *    Generation-Date:   03.09.2024  15:13:28  
 *    Generated by user: uiv10169
 * Filename:   $Workfile$
 * Revision:   $Revision: 1.2 $
 * Author:     $Author: Ling Jiaming (uiv10169) (uiv10169) $
 * Date:       $Date: 2024/09/05 08:20:31CEST $
 * Changes:    $Log: ipl_hook_rx_prim_data.c  $
 * Changes:    Revision 1.2 2024/09/05 08:20:31CEST Ling Jiaming (uiv10169) (uiv10169) 
 * Changes:    add new interface Pl_VehSysDwnTiMins
 * 
****************************************************************************/
/*lint -esym(750,IPL_HOOK_RX_PRIM_DATA_C) */
#define IPL_HOOK_RX_PRIM_DATA_C
#include <intc_sigcv_mc1_im.h>




/* System-Variable definition */
#define MEM_DATA MEM_DATA_PUBLIC_8
#include <gmem.h>
ICS_PL_FLAG Pl_AntiJerkEna;


/* System-Variable definition */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
ICS_PL_FLOAT Pl_AntiJerkEnaSpdThd;


/* System-Variable definition */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
ICS_PL_FLOAT Pl_AntiJerkEnaSpdThd_Prim;


/* System-Variable definition */
#define MEM_DATA MEM_DATA_PUBLIC_8
#include <gmem.h>
ICS_PL_FLAG Pl_AntiJerkEna_Prim;


/* System-Variable definition */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
ICS_PL_FLOAT Pl_AntiJerkGain;


/* System-Variable definition */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
ICS_PL_FLOAT Pl_AntiJerkGain_Prim;


/* System-Variable definition */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
ICS_PL_FLOAT Pl_AntiJerkTqLimMax;


/* System-Variable definition */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
ICS_PL_FLOAT Pl_AntiJerkTqLimMax_Prim;


/* System-Variable definition */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
ICS_PL_FLOAT Pl_AntiJerkTqLimMin;


/* System-Variable definition */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
ICS_PL_FLOAT Pl_AntiJerkTqLimMin_Prim;


/* System-Variable definition */
#define MEM_DATA MEM_DATA_PUBLIC_8
#include <gmem.h>
ICS_PL_FLAG Pl_LvUHvsReqExtEna;


/* System-Variable definition */
#define MEM_DATA MEM_DATA_PUBLIC_8
#include <gmem.h>
ICS_PL_FLAG Pl_LvUHvsReqExtEna_Prim;


/* System-Variable definition */
#define MEM_DATA MEM_DATA_PUBLIC_8
#include <gmem.h>
ICS_PL_U8 Pl_VehCluAxleSet;


/* System-Variable definition */
#define MEM_DATA MEM_DATA_PUBLIC_8
#include <gmem.h>
ICS_PL_U8 Pl_VehCluAxleSet_Prim;


/* System-Variable definition */
#define MEM_DATA MEM_DATA_PUBLIC_16
#include <gmem.h>
ICS_PL_FLOAT Pl_VehCooltInvInT_North;


/* System-Variable definition */
#define MEM_DATA MEM_DATA_PUBLIC_16
#include <gmem.h>
ICS_PL_FLOAT Pl_VehCooltInvInT_North_Prim;


/* System-Variable definition */
#define MEM_DATA MEM_DATA_PUBLIC_16
#include <gmem.h>
ICS_PL_FLOAT Pl_VehCooltInvInT_South;


/* System-Variable definition */
#define MEM_DATA MEM_DATA_PUBLIC_16
#include <gmem.h>
ICS_PL_FLOAT Pl_VehCooltInvInT_South_Prim;


/* System-Variable definition */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
ICS_PL_FLOAT Pl_VehCooltInvInVolFlow;


/* System-Variable definition */
#define MEM_DATA MEM_DATA_PUBLIC_8
#include <gmem.h>
ICS_PL_FLAG Pl_VehCooltInvInVolFlowVld;


/* System-Variable definition */
#define MEM_DATA MEM_DATA_PUBLIC_8
#include <gmem.h>
ICS_PL_FLAG Pl_VehCooltInvInVolFlowVld_Prim;


/* System-Variable definition */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
ICS_PL_FLOAT Pl_VehCooltInvInVolFlow_Prim;


/* System-Variable definition */
#define MEM_DATA MEM_DATA_PUBLIC_16
#include <gmem.h>
ICS_PL_U16 Pl_VehHvDcILimMax;


/* System-Variable definition */
#define MEM_DATA MEM_DATA_PUBLIC_16
#include <gmem.h>
ICS_PL_U16 Pl_VehHvDcILimMax_Prim;


/* System-Variable definition */
#define MEM_DATA MEM_DATA_PUBLIC_16
#include <gmem.h>
ICS_PL_U16 Pl_VehHvDcILimMin;


/* System-Variable definition */
#define MEM_DATA MEM_DATA_PUBLIC_16
#include <gmem.h>
ICS_PL_U16 Pl_VehHvDcILimMin_Prim;


/* System-Variable definition */
#define MEM_DATA MEM_DATA_PUBLIC_8
#include <gmem.h>
ICS_PL_FLAG Pl_VehNetMngtReq;


/* System-Variable definition */
#define MEM_DATA MEM_DATA_PUBLIC_8
#include <gmem.h>
ICS_PL_FLAG Pl_VehNetMngtReq_Prim;


/* System-Variable definition */
#define MEM_DATA MEM_DATA_PUBLIC_8
#include <gmem.h>
ICS_PL_U8 Pl_VehPeModeReq;


/* System-Variable definition */
#define MEM_DATA MEM_DATA_PUBLIC_8
#include <gmem.h>
ICS_PL_U8 Pl_VehPeModeReq_Prim;


/* System-Variable definition */
#define MEM_DATA MEM_DATA_PUBLIC_16
#include <gmem.h>
ICS_PL_U16 Pl_VehSysDwnTiMins;


/* System-Variable definition */
#define MEM_DATA MEM_DATA_PUBLIC_16
#include <gmem.h>
ICS_PL_U16 Pl_VehSysDwnTiMins_Prim;


/* System-Variable definition */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
ICS_PL_FLOAT Pl_VehWhlSpd1;


/* System-Variable definition */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
ICS_PL_FLOAT Pl_VehWhlSpd1_Prim;


/* System-Variable definition */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
ICS_PL_FLOAT Pl_VehWhlSpd2;


/* System-Variable definition */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
ICS_PL_FLOAT Pl_VehWhlSpd2_Prim;


/* System-Variable definition */
#define MEM_DATA MEM_DATA_PUBLIC_16
#include <gmem.h>
ICS_PL_S16 Pl_VehWhlSpdTgt;


/* System-Variable definition */
#define MEM_DATA MEM_DATA_PUBLIC_16
#include <gmem.h>
ICS_PL_S16 Pl_VehWhlSpdTgt_Prim;


/* System-Variable definition */
#define MEM_DATA MEM_DATA_PUBLIC_8
#include <gmem.h>
ICS_PL_FLAG Pl_VehWhlSpdVld1;


/* System-Variable definition */
#define MEM_DATA MEM_DATA_PUBLIC_8
#include <gmem.h>
ICS_PL_FLAG Pl_VehWhlSpdVld1_Prim;


/* System-Variable definition */
#define MEM_DATA MEM_DATA_PUBLIC_8
#include <gmem.h>
ICS_PL_FLAG Pl_VehWhlSpdVld2;


/* System-Variable definition */
#define MEM_DATA MEM_DATA_PUBLIC_8
#include <gmem.h>
ICS_PL_FLAG Pl_VehWhlSpdVld2_Prim;


/* System-Variable definition */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
ICS_PL_FLOAT Pl_VehWhlTqMaxLim;


/* System-Variable definition */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
ICS_PL_FLOAT Pl_VehWhlTqMaxLim_Prim;


/* System-Variable definition */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
ICS_PL_FLOAT Pl_VehWhlTqMinLim;


/* System-Variable definition */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
ICS_PL_FLOAT Pl_VehWhlTqMinLim_Prim;


/* System-Variable definition */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
ICS_PL_FLOAT Pl_VehWhlTqTgt;


/* System-Variable definition */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
ICS_PL_FLOAT Pl_VehWhlTqTgt_Prim;
