/****************************************************************************
 * COPYRIGHT VITESCO TECHNOLOGIES GROUP AG (EXCLUSIVE RIGHTS) 
 * Confidential
 * 
 * The reproduction, transmission or use of this document or its
 * contents is not permitted without express written authority.
 * Offenders will be liable for damages. All rights, including rights
 * created by patent grant or registration of a utility model or design,
 * are reserved.
 *---------------------------------------------------------------------------
 * 
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 * !!! This file is generated by Signal Mapper (SIMA) Code-Generator !!!
 * !!! Do NOT modify this file manually                            !!!
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 * 
 * Purpose:    PL Hook Header for data H File
 * 
 * Processor:  independent
 * Tool chain: 
 *    CG-Version:        6.2.0
 *    Schema-Version:    1.18.0
 *    Generation-Date:   29.08.2024  16:59:16  
 *    Generated by user: uiv00534
 * Filename:   $Workfile$
 * Revision:   $Revision: 1.1 $
 * Author:     $Author: Zhang Yi (uiv00534) (uiv00534) $
 * Date:       $Date: 2024/09/03 03:20:48CEST $
 * Changes:    $Log: ipl_hook_tx_prim_data.h  $
 * Changes:    Revision 1.1 2024/09/03 03:20:48CEST Zhang Yi (uiv00534) (uiv00534) 
 * Changes:    Initial revision
 * Changes:    Member added to project /ES/FS/0G/H0D/0A/bsw/intc/intc_sigcv_mc1/i/project.pj
 * 
****************************************************************************/
#ifndef IPL_HOOK_TX_PRIM_DATA_H
#define IPL_HOOK_TX_PRIM_DATA_H



/* System-Variable declaration for Pl_LvNEmOverDet */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
extern ICS_PL_FLOAT Pl_LvNEmOverDet;

/* System-Variable declaration for Pl_StEmRedMax */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_8
#include <gmem.h>
extern ICS_PL_U8 Pl_StEmRedMax;

/* System-Variable declaration for Pl_StEmRedMin */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_8
#include <gmem.h>
extern ICS_PL_U8 Pl_StEmRedMin;

/* System-Variable declaration for Pl_PwrLossElInvt */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
extern ICS_PL_FLOAT Pl_PwrLossElInvt;

/* System-Variable declaration for Pl_PwrLossInvtMaxEstim */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
extern ICS_PL_FLOAT Pl_PwrLossInvtMaxEstim;

/* System-Variable declaration for Pl_EmRotorTEstimd */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
extern ICS_PL_FLOAT Pl_EmRotorTEstimd;

/* System-Variable declaration for Pl_PeIgbtDiodeT */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
extern ICS_PL_FLOAT Pl_PeIgbtDiodeT;

/* System-Variable declaration for Pl_EmStatorTHotSpotEstimd */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
extern ICS_PL_FLOAT Pl_EmStatorTHotSpotEstimd;

/* System-Variable declaration for Pl_CluAxleSt */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_8
#include <gmem.h>
extern ICS_PL_U8 Pl_CluAxleSt;

/* System-Variable declaration for Pl_AcvDchaSts */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_8
#include <gmem.h>
extern ICS_PL_U8 Pl_AcvDchaSts;

/* System-Variable declaration for Pl_PeModeAct */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_8
#include <gmem.h>
extern ICS_PL_U8 Pl_PeModeAct;

/* System-Variable declaration for Pl_WhlTqEstimdAct */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
extern ICS_PL_FLOAT Pl_WhlTqEstimdAct;

/* System-Variable declaration for Pl_WhlTqMaxEstimdLimAct */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
extern ICS_PL_FLOAT Pl_WhlTqMaxEstimdLimAct;

/* System-Variable declaration for Pl_WhlTqMinEstimdLimAct */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
extern ICS_PL_FLOAT Pl_WhlTqMinEstimdLimAct;

/* System-Variable declaration for Pl_HvDcIEstimd */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_32
#include <gmem.h>
extern ICS_PL_FLOAT Pl_HvDcIEstimd;

/* System-Variable declaration for Pl_HvDcUMeasd */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_16
#include <gmem.h>
extern ICS_PL_S16 Pl_HvDcUMeasd;

/* System-Variable declaration for Pl_LvStPosnRotorVld */
/* ==================================================================== */
#define MEM_DATA MEM_DATA_PUBLIC_8
#include <gmem.h>
extern ICS_PL_U8 Pl_LvStPosnRotorVld;


#include <gmem.h>
#endif
