/****************************************************************************
 * COPYRIGHT VITESCO TECHNOLOGIES GROUP AG (EXCLUSIVE RIGHTS) 
 * Confidential
 * 
 * The reproduction, transmission or use of this document or its
 * contents is not permitted without express written authority.
 * Offenders will be liable for damages. All rights, including rights
 * created by patent grant or registration of a utility model or design,
 * are reserved.
 *---------------------------------------------------------------------------
 * 
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 * !!! This file is generated by Signal Mapper (SIMA) Code-Generator !!!
 * !!! Do NOT modify this file manually                            !!!
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 * 
 * Purpose:    PL Hook Header for MCR
 * 
 * Processor:  independent
 * Tool chain: 
 *    CG-Version:        6.2.0
 *    Schema-Version:    1.18.0
 *    Generation-Date:   03.09.2024  15:13:28  
 *    Generated by user: uiv10169
 * Filename:   $Workfile$
 * Revision:   $Revision: 1.2 $
 * Author:     $Author: Ling Jiaming (uiv10169) (uiv10169) $
 * Date:       $Date: 2024/09/05 08:20:29CEST $
 * Changes:    $Log: ipl_hook_rx_sec_mcr.h  $
 * Changes:    Revision 1.2 2024/09/05 08:20:29CEST Ling Jiaming (uiv10169) (uiv10169) 
 * Changes:    add new interface Pl_VehSysDwnTiMins
 * 
****************************************************************************/
#ifndef IPL_HOOK_RX_SEC_MCR_H
#define IPL_HOOK_RX_SEC_MCR_H

#undef ACTION_ID_NONE
#undef RUNNABLE_ID_NONE
#define ACTION_ID_NONE 0
#define RUNNABLE_ID_NONE 0

#define ACTION_ID_PL_Cvt_EduSec_EMU_EDU_antiJerkEnable 92
#define ACTION_ID_PL_Cvt_EduSec_EMU_EDU_antiJerkGain 93
#define ACTION_ID_PL_Cvt_EduSec_EMU_EDU_antiJerkMaxTorq 94
#define ACTION_ID_PL_Cvt_EduSec_EMU_EDU_antiJerkMinTorq 95
#define ACTION_ID_PL_Cvt_EduSec_EMU_EDU_antiJerkSpeedThres 96
#define ACTION_ID_PL_Cvt_EduSec_EMU_EDU_clutchReq 97
#define ACTION_ID_PL_Cvt_EduSec_EMU_EDU_hvOnRequest 98
#define ACTION_ID_PL_Cvt_EduSec_EMU_EDU_iLimitMax 99
#define ACTION_ID_PL_Cvt_EduSec_EMU_EDU_iLimitMin 100
#define ACTION_ID_PL_Cvt_EduSec_EMU_EDU_inverterStateReq 101
#define ACTION_ID_PL_Cvt_EduSec_EMU_EDU_outputShaftTorqueReq 102
#define ACTION_ID_PL_Cvt_EduSec_EMU_EDU_outputShaftTrqMax 103
#define ACTION_ID_PL_Cvt_EduSec_EMU_EDU_outputShaftTrqMin 104
#define ACTION_ID_PL_Cvt_EduSec_EMU_EDU_pwtCoolantFlow 105
#define ACTION_ID_PL_Cvt_EduSec_EMU_EDU_pwtCoolantFlowValid 106
#define ACTION_ID_PL_Cvt_EduSec_EMU_EDU_systemDowntime 107
#define ACTION_ID_PL_Cvt_EduSec_EMU_EDU_wheelRpmGbxSide 108
#define ACTION_ID_PL_Cvt_EduSec_EMU_EDU_wheelRpmMtrSide 109
#define ACTION_ID_PL_Cvt_EduSec_EMU_EDU_wheelRpmValidGbxSide 110
#define ACTION_ID_PL_Cvt_EduSec_EMU_EDU_wheelRpmValidMtrSide 111
#define ACTION_ID_PL_Cvt_EduSec_EMU_EDU_wheelSpeedTarget 112
#define ACTION_ID_PL_Cvt_EduSec_EMU_nmStateReq 113
#define ACTION_ID_PL_Cvt_EduSec_TBC_EMU_inverterInletNorthTemp 114
#define ACTION_ID_PL_Cvt_EduSec_TBC_EMU_inverterInletSouthTemp 115
#endif

#if !(defined RUNNABLE_ID || defined ACTION_ID)
#error "No RUNNABLE_ID or ACTION_ID defined"
#endif
#ifndef RUNNABLE_ID
#define RUNNABLE_ID RUNNABLE_ID_NONE
#endif
#ifndef ACTION_ID
#define ACTION_ID ACTION_ID_NONE
#endif


/* Getters and setters for everyone */
#ifndef SET_Pl_AntiJerkEna_Sec
  #define SET_Pl_AntiJerkEna_Sec(x) (Pl_AntiJerkEna_Sec=(x))
#endif
#ifndef SET_Pl_AntiJerkEnaSpdThd_Sec
  #define SET_Pl_AntiJerkEnaSpdThd_Sec(x) (Pl_AntiJerkEnaSpdThd_Sec=(x))
#endif
#ifndef SET_Pl_AntiJerkGain_Sec
  #define SET_Pl_AntiJerkGain_Sec(x) (Pl_AntiJerkGain_Sec=(x))
#endif
#ifndef SET_Pl_AntiJerkTqLimMax_Sec
  #define SET_Pl_AntiJerkTqLimMax_Sec(x) (Pl_AntiJerkTqLimMax_Sec=(x))
#endif
#ifndef SET_Pl_AntiJerkTqLimMin_Sec
  #define SET_Pl_AntiJerkTqLimMin_Sec(x) (Pl_AntiJerkTqLimMin_Sec=(x))
#endif
#ifndef SET_Pl_LvUHvsReqExtEna_Sec
  #define SET_Pl_LvUHvsReqExtEna_Sec(x) (Pl_LvUHvsReqExtEna_Sec=(x))
#endif
#ifndef SET_Pl_VehCluAxleSet_Sec
  #define SET_Pl_VehCluAxleSet_Sec(x) (Pl_VehCluAxleSet_Sec=(x))
#endif
#ifndef SET_Pl_VehCooltInvInT_North_Sec
  #define SET_Pl_VehCooltInvInT_North_Sec(x) (Pl_VehCooltInvInT_North_Sec=(x))
#endif
#ifndef SET_Pl_VehCooltInvInT_South_Sec
  #define SET_Pl_VehCooltInvInT_South_Sec(x) (Pl_VehCooltInvInT_South_Sec=(x))
#endif
#ifndef SET_Pl_VehCooltInvInVolFlow_Sec
  #define SET_Pl_VehCooltInvInVolFlow_Sec(x) (Pl_VehCooltInvInVolFlow_Sec=(x))
#endif
#ifndef SET_Pl_VehCooltInvInVolFlowVld_Sec
  #define SET_Pl_VehCooltInvInVolFlowVld_Sec(x) (Pl_VehCooltInvInVolFlowVld_Sec=(x))
#endif
#ifndef SET_Pl_VehHvDcILimMax_Sec
  #define SET_Pl_VehHvDcILimMax_Sec(x) (Pl_VehHvDcILimMax_Sec=(x))
#endif
#ifndef SET_Pl_VehHvDcILimMin_Sec
  #define SET_Pl_VehHvDcILimMin_Sec(x) (Pl_VehHvDcILimMin_Sec=(x))
#endif
#ifndef SET_Pl_VehNetMngtReq_Sec
  #define SET_Pl_VehNetMngtReq_Sec(x) (Pl_VehNetMngtReq_Sec=(x))
#endif
#ifndef SET_Pl_VehPeModeReq_Sec
  #define SET_Pl_VehPeModeReq_Sec(x) (Pl_VehPeModeReq_Sec=(x))
#endif
#ifndef SET_Pl_VehSysDwnTiMins_Sec
  #define SET_Pl_VehSysDwnTiMins_Sec(x) (Pl_VehSysDwnTiMins_Sec=(x))
#endif
#ifndef SET_Pl_VehWhlSpd1_Sec
  #define SET_Pl_VehWhlSpd1_Sec(x) (Pl_VehWhlSpd1_Sec=(x))
#endif
#ifndef SET_Pl_VehWhlSpd2_Sec
  #define SET_Pl_VehWhlSpd2_Sec(x) (Pl_VehWhlSpd2_Sec=(x))
#endif
#ifndef SET_Pl_VehWhlSpdTgt_Sec
  #define SET_Pl_VehWhlSpdTgt_Sec(x) (Pl_VehWhlSpdTgt_Sec=(x))
#endif
#ifndef SET_Pl_VehWhlSpdVld1_Sec
  #define SET_Pl_VehWhlSpdVld1_Sec(x) (Pl_VehWhlSpdVld1_Sec=(x))
#endif
#ifndef SET_Pl_VehWhlSpdVld2_Sec
  #define SET_Pl_VehWhlSpdVld2_Sec(x) (Pl_VehWhlSpdVld2_Sec=(x))
#endif
#ifndef SET_Pl_VehWhlTqMaxLim_Sec
  #define SET_Pl_VehWhlTqMaxLim_Sec(x) (Pl_VehWhlTqMaxLim_Sec=(x))
#endif
#ifndef SET_Pl_VehWhlTqMinLim_Sec
  #define SET_Pl_VehWhlTqMinLim_Sec(x) (Pl_VehWhlTqMinLim_Sec=(x))
#endif
#ifndef SET_Pl_VehWhlTqTgt_Sec
  #define SET_Pl_VehWhlTqTgt_Sec(x) (Pl_VehWhlTqTgt_Sec=(x))
#endif

#undef RUNNABLE_ID
#define RUNNABLE_ID RUNNABLE_ID_NONE
#undef ACTION_ID
#define ACTION_ID ACTION_ID_NONE

#if !((RUNNABLE_ID == RUNNABLE_ID_NONE) && (ACTION_ID == RUNNABLE_ID_NONE))
#error "Illegal RUNNABLE_ID or ACTION_ID found"
#endif


