/****************************************************************************
 * COPYRIGHT VITESCO TECHNOLOGIES GROUP AG (EXCLUSIVE RIGHTS) 
 * Confidential
 * 
 * The reproduction, transmission or use of this document or its
 * contents is not permitted without express written authority.
 * Offenders will be liable for damages. All rights, including rights
 * created by patent grant or registration of a utility model or design,
 * are reserved.
 *---------------------------------------------------------------------------
 * 
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 * !!! This file is generated by Signal Mapper (SIMA) Code-Generator !!!
 * !!! Do NOT modify this file manually                            !!!
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 * 
 * Purpose:    PL Hook Header
 * 
 * Processor:  independent
 * Tool chain: 
 *    CG-Version:        6.2.0
 *    Schema-Version:    1.18.0
 *    Generation-Date:   29.08.2024  16:59:16  
 *    Generated by user: uiv00534
 * Filename:   $Workfile$
 * Revision:   $Revision: 1.1 $
 * Author:     $Author: Zhang Yi (uiv00534) (uiv00534) $
 * Date:       $Date: 2024/09/03 03:20:52CEST $
 * Changes:    $Log: ipl_hook_tx_sec.h  $
 * Changes:    Revision 1.1 2024/09/03 03:20:52CEST Zhang Yi (uiv00534) (uiv00534) 
 * Changes:    Initial revision
 * Changes:    Member added to project /ES/FS/0G/H0D/0A/bsw/intc/intc_sigcv_mc1/i/project.pj
 * 
****************************************************************************/
#ifndef IPL_HOOK_TX_SEC_H
#define IPL_HOOK_TX_SEC_H

#include <ipl_pcnf.h>


/* Variant-IDs */
#ifndef BSample
  #define BSample 1U
#endif


#define  MEM_CODE            ICS_PL_MEM_CODE_SERVICE
#include <gmem.h>


/* PL2Com Definition for EduSec_EDU_activeDischFeatEn */
#define PL2COM_DEF_PL_CVT_EDUSEC_EDU_ACTIVEDISCHFEATEN
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduSec_EDU_activeDischFeatEn(void);
/* PL2Com Definition for EduSec_EDU_clutchState */
#define PL2COM_DEF_PL_CVT_EDUSEC_EDU_CLUTCHSTATE
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduSec_EDU_clutchState(void);
/* PL2Com Definition for EduSec_EDU_comStatusPrimary */
#define PL2COM_DEF_PL_CVT_EDUSEC_EDU_COMSTATUSPRIMARY
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduSec_EDU_comStatusPrimary(void);
/* PL2Com Definition for EduSec_EDU_comStatusSecondary */
#define PL2COM_DEF_PL_CVT_EDUSEC_EDU_COMSTATUSSECONDARY
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduSec_EDU_comStatusSecondary(void);
/* PL2Com Definition for EduSec_EDU_currentDc */
#define PL2COM_DEF_PL_CVT_EDUSEC_EDU_CURRENTDC
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduSec_EDU_currentDc(void);
/* PL2Com Definition for EduSec_EDU_heatPower */
#define PL2COM_DEF_PL_CVT_EDUSEC_EDU_HEATPOWER
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduSec_EDU_heatPower(void);
/* PL2Com Definition for EduSec_EDU_heatPowerLimit */
#define PL2COM_DEF_PL_CVT_EDUSEC_EDU_HEATPOWERLIMIT
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduSec_EDU_heatPowerLimit(void);
/* PL2Com Definition for EduSec_EDU_igbtTemp */
#define PL2COM_DEF_PL_CVT_EDUSEC_EDU_IGBTTEMP
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduSec_EDU_igbtTemp(void);
/* PL2Com Definition for EduSec_EDU_inverterState */
#define PL2COM_DEF_PL_CVT_EDUSEC_EDU_INVERTERSTATE
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduSec_EDU_inverterState(void);
/* PL2Com Definition for EduSec_EDU_nmAbleToSleep */
#define PL2COM_DEF_PL_CVT_EDUSEC_EDU_NMABLETOSLEEP
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduSec_EDU_nmAbleToSleep(void);
/* PL2Com Definition for EduSec_EDU_nmSleepError */
#define PL2COM_DEF_PL_CVT_EDUSEC_EDU_NMSLEEPERROR
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduSec_EDU_nmSleepError(void);
/* PL2Com Definition for EduSec_EDU_nmState */
#define PL2COM_DEF_PL_CVT_EDUSEC_EDU_NMSTATE
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduSec_EDU_nmState(void);
/* PL2Com Definition for EduSec_EDU_outputShaftTorque */
#define PL2COM_DEF_PL_CVT_EDUSEC_EDU_OUTPUTSHAFTTORQUE
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduSec_EDU_outputShaftTorque(void);
/* PL2Com Definition for EduSec_EDU_outputShaftTorqueLimMax */
#define PL2COM_DEF_PL_CVT_EDUSEC_EDU_OUTPUTSHAFTTORQUELIMMAX
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduSec_EDU_outputShaftTorqueLimMax(void);
/* PL2Com Definition for EduSec_EDU_outputShaftTorqueLimMin */
#define PL2COM_DEF_PL_CVT_EDUSEC_EDU_OUTPUTSHAFTTORQUELIMMIN
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduSec_EDU_outputShaftTorqueLimMin(void);
/* PL2Com Definition for EduSec_EDU_outputShaftTorqueValid */
#define PL2COM_DEF_PL_CVT_EDUSEC_EDU_OUTPUTSHAFTTORQUEVALID
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduSec_EDU_outputShaftTorqueValid(void);
/* PL2Com Definition for EduSec_EDU_rotorPosition */
#define PL2COM_DEF_PL_CVT_EDUSEC_EDU_ROTORPOSITION
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduSec_EDU_rotorPosition(void);
/* PL2Com Definition for EduSec_EDU_rotorPositionValid */
#define PL2COM_DEF_PL_CVT_EDUSEC_EDU_ROTORPOSITIONVALID
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduSec_EDU_rotorPositionValid(void);
/* PL2Com Definition for EduSec_EDU_rotorSpeed */
#define PL2COM_DEF_PL_CVT_EDUSEC_EDU_ROTORSPEED
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduSec_EDU_rotorSpeed(void);
/* PL2Com Definition for EduSec_EDU_rotorSpeedValid */
#define PL2COM_DEF_PL_CVT_EDUSEC_EDU_ROTORSPEEDVALID
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduSec_EDU_rotorSpeedValid(void);
/* PL2Com Definition for EduSec_EDU_rotorTemp */
#define PL2COM_DEF_PL_CVT_EDUSEC_EDU_ROTORTEMP
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduSec_EDU_rotorTemp(void);
/* PL2Com Definition for EduSec_EDU_statorTemp */
#define PL2COM_DEF_PL_CVT_EDUSEC_EDU_STATORTEMP
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduSec_EDU_statorTemp(void);
/* PL2Com Definition for EduSec_EDU_voltageDc */
#define PL2COM_DEF_PL_CVT_EDUSEC_EDU_VOLTAGEDC
/* Signal-Conversion */
extern ICS_PL_RETURN_TYPE PL_Cvt_EduSec_EDU_voltageDc(void);
#include <gmem.h>
#endif
